export default {

  /* Layouts */
  _lt: {

    default: {
      cookiesBanner: 'We use cookies 🍪 to provide the best experience. By continuing to use our website, you agree to our cookies policy. {button}',
      readMore: 'Read more...',
    },

  },

  /* Common */
  _cm: {
    lastRevision: 'Last updated:',
    contactUs: 'Contact us',
    followUs: 'Follow us',
    reviewUs: 'Review us',
    close: 'Close',
    cancel: 'Cancel',
  },

  /* Languages */
  _lg: {
    french: 'French',
    english: 'English',
    polish: 'Polish',
    spanish: 'Spanish',
    swedish: 'Swedish',
    turkish: 'Turkish',
    indonesian: 'Indonesian',
    portuguese: 'Portuguese',
    simplifiedChinese: 'Simplified Chinese',
    traditionalChinese: 'Traditional Chinese',
    dutch: 'Dutch',
    german: 'German',
    arabic: 'Arabic',
  },

  /* Pluralization */
  _pl: {
    seconds: 'second | second | seconds',
    features: 'feature | feature | features',
    results: 'result | result | results',
  },

  /* Components */
  _cp: {

    /* Header component */
    header: {
      logIn: 'Log in',
      helloYou: 'Hello {username} 👋🏻',
      myAccount: 'My account',
      switchAccount: 'Switch account',
      logout: 'Log out',
    },

    /* Footer component */
    footer: {
      madeWithLove: 'Affinitweet is a Twitter-based statistics and entertainment platform created in 2015 with ❤️ in France.',
      allRightsReserved: 'All rights reserved.',
      stripeClimate: '1% of our revenue is donated to CO₂ reduction initiatives.',
      about: 'About',
      changelog: 'Changelog',
      legal: 'Legal',
      partners: 'Partners',
    },

    stateButton: {
      hold: 'Hold to confirm',
      submit: 'Click to confirm',
      loading: 'Action in process...',
      cancel: 'Cancel',
    },

    clearHistory: {
      title: 'Clear history',
      description: 'By cleaning up your history, all information and images of your currently saved results will be deleted.',
      description2: 'You won\'t be able to see your previous results after this cleaning, do you really want to perform this action?',
      holdButton: 'Hold to clear',
      loadingButton: 'Clearing history...',
      successModal: 'Your history has been cleared.',
    },

    deleteAccount: {
      title: 'Delete account',
      description: 'Did something go wrong? Tell us on our Twitter account so we can improve!',
      description2: 'By deleting your account, all data about you will be deleted, including your history. No data will be kept and you will be automatically logged out of Affinitweet.',
      description3: 'You will not be able to retrieve your current account after this deletion, do you really want to perform this action?',
      holdButton: 'Hold to delete',
      loadingButton: 'Deleting account...',
      successModal: 'Your account has been deleted.',
    },

    twitterDM: {
      startWritingToPreview: 'Start writing to preview your content here!',
      now: 'Now',
    },

    welcomeMessage: {
      creationDate: 'Created {date} with {source}',
      soon: 'soon',
      draft: 'Draft',
      inactive: 'Inactive',
      active: 'Active',
      submit: 'Submit',
      cancel: 'Cancel',
      edit: 'Edit',
      enable: 'Enable',
      disable: 'Disable',
      delete: 'Delete',
      writeContent: 'Write the content of your message',
      writeContentPlaceholder: 'Write your Welcome Message here...',
      addOptionalMedia: 'Add a media (optionnal)',
      filePlaceholder: 'Drag & drop a media or click here 🖼',
      selectMessageType: 'Select the type of message',
      classic: 'Classic',
      button: 'Buttons',
      buttonLabelPlaceholder: 'Label',
      buttonURLPlaceholder: 'https://...',
      quickReply: 'Quick Reply',
      quickReplyPlaceholder: 'Label',
      quickReplyDescriptionPlaceholder: 'Description',
      previewResult: 'Preview your Welcome Message in real-time',
      confirmDeleting: 'Are you sure you want to delete this Welcome Message?',
      confirmEnabling: 'Are you sure you want to enable this Welcome Message? It will disable the other one currently active.',
      confirmDisabling: 'Are you sure you want to disable this Welcome Message ',
    },

    welcomeMessageEditor: {
      twitterDocumentation: "What's a Welcome Message ? (Twitter)",
      helpdeskDocumentation: 'How does the Welcome Message Editor work?',
      fetchingWelcomeMessages: 'Fetching Welcome Messages...',
      addWelcomeMessage: 'Add a Welcome Message',
    },

    deepLinkGenerator: {
      twitterDocumentation: "What's a Deep Link ? (Twitter)",
      helpdeskDocumentation: 'How does the Deep Link Generator work?',
      inputPlaceholder: 'Write the content that will be pre-filled to the user!',
      attachWelcomeMessage: 'Attach a Welcome Message',
      youDontHaveWelcomeMessageYet: "You don't have any Welcome Message yet.",
      createNewWelcomeMessage: 'Create a new Welcome Message',
      copyLink: 'Copy link',
      copied: 'Copied',
      generatedLinkWillBeHere: 'The link to add to the tweet will be generated here.',
    },

    idUsernameConverter: {
      helpdeskDocumentation: 'How does the ID <> Username Converter work?',
      entryFormat: 'Entry format',
      inputPlaceholder: 'Write or paste one or more IDs/usernames here!',
      copied: 'Copied',
      converting: 'Converting...',
      noResult: 'No result.',
      errorOccured: 'An error occured.',
      viewProfileOnTwitter: 'View profile on Twitter',
    },

    friendsFollowersManager: {
      helpdeskDocumentation: 'How does the Friends/Followers Manager work?',
      lastUpdate: 'Last update {date}',
      updateButton: 'Update',
      all: 'All',
      followers: 'Followers',
      following: 'Following',
      mutuals: 'Mutuals',
      filters: {
        title: 'Filters',
        protected: 'Private accounts',
        verified: 'Verified accounts',
      },
      search: 'Search...',
      fetching: 'Fetching data...',
      noResults: 'Aucun résultat ne correspond à ta recherche, essaie autrement !',
      name: 'Name',
      relationship: 'Relationship',
      tweets: 'Tweets',
      registration: 'Registration',
      showMore: 'Show {step} more {results} ({currentShowed}/{totalResults})',
      screenTooSmall: 'Screen too small',
      screenTooSmallDescription: "The Friends/Followers Manager is a comprehensive tool displaying a lot of data, the use on mobile was not made possible to not degrade the experience. You can try to switch to landscape mode to see if it works, if it doens't work you will have to use a larger screen size 😇",
    },

    managerItem: {
      followingYou: 'Following you',
      followedByYou: 'Followed',
      mutualFollow: 'Mutual follow',
      showProfile: 'Show profile',
      follow: 'Follow',
      unfollow: 'Unfollow',
      sendDM: 'Send a DM',
      block: 'Block',
      reportAndBlock: 'Report and block',
    },

  },

  /* Features */
  _ft: {

    new: 'New',
    popular: 'Popular',
    real: 'Real',
    fun: 'Fun',
    beta: 'Beta',
    others: 'Others',

    list: {

      friendships: {
        description: 'Everything you need to know about the links between you and a user! 🙌',
        longDescription: 'Thanks to Friendships you will know how much you are friends with another user of your choice: the more blue pellets you have, the stronger the links are! Enter the Twitter nickname of the chosen person and discover your Friendships!',
      },
      'common-friends': {
        description: 'Discover your friends in common with another user! 👥',
        longDescription: 'The Common Friends allows you to discover the subscriptions/friends you have in common with another person. Do you have the same tastes, and how much?',
      },
      'top-friends': {
        description: 'Discover your best Twitter friends of late! 🤗',
        longDescription: 'The Top Friends allows you to know who your best friends are on Twitter. We establish a ranking by analyzing the information sent and received by your account. Then we count, add and sort them to generate your Top Friends!',
      },
      'famous-followers': {
        description: 'Discover the most popular people in your followers! 💅',
        longDescription: 'The Famous Followers allows you to know which people have the most followers among your followers. We collect each of your followers and their number of followers and sort them to generate your Famous Followers!',
      },
      valentine: {
        description: 'We know who your Valentine will be this year... What about you? 💏',
        longDescription: 'We keep the algorithm of this feature secret. All we can say is that we are trying to stick to reality, will our Valentine delight you... ?',
      },
      'twitter-activity': {
        description: 'Discover the summary of your activity and your Twitter statistics 📊',
        longDescription: 'Thanks to Twitter Activity, you will know when you tweet most often, how many interactions (impressions, retweets, likes, replies) you have in total and the distribution of your tweets.',
      },
      'first-follower': {
        description: 'Discover who\'s the first person who followed you on Twitter 1️⃣',
        longDescription: 'Thanks to the First Follower, you\'ll know who is your first follower and when they followed you (or the oldest one, because if you\'ve been unfollowed in the meantime, we can\'t know).',
      },
      'first-following': {
        description: 'Discover who\'s the first person you followed on Twitter 1️⃣',
        longDescription: 'Thanks to the First Following, you\'ll know who is your first following and when you followed them (or the oldest one, because if you\'ve unfollowed people in the meantime, we can\'t know).',
      },
      'secret-crush': {
        description: 'Someone loves you in secret... and hides it from you... 😳',
        longDescription: 'We keep the algorithm of this feature secret. All we can say is that your Secret Crush will impress you, good or bad?',
      },
      'hidden-twin': {
        description: 'Yes, you have a hidden twin.... who the hell is it? 🤔',
        longDescription: 'We keep the algorithm of this feature secret. All we can say is that your Hidden Twin will impress you, good or bad?',
      },
      'stolen-kiss': {
        description: 'Who wants to steal a kiss from you on a street corner? 💋',
        longDescription: 'We keep the algorithm of this feature secret. All we can say is that your Stolen Kiss will impress you, good or bad?',
      },
      'may-day': {
        description: 'Who\'s your best bouquet for this year? 💐',
        longDescription: 'We keep the algorithm of this feature secret. All we can say is that you\'re going to make someone very happy!',
      },
      'halloween-duo': {
        description: 'Who will you be most afraid with this year? 🎃👻',
        longDescription: 'We keep the algorithm of this feature secret. All we can say is that you\'re going to be scary for Halloween this year!',
      },
      'tweet-rate': {
        description: 'Compare your tweet rate with another user! 📊',
        longDescription: 'The Tweet Rate allows you to know the average number of tweets you publish per day since you registered on Twitter and compare yourself with another person! Are you the most active?',
      },
      'first-to-follow': {
        description: 'Find out when you\'ve been following a user and vice versa! 😮',
        longDescription: 'The First To Follow allows you to discover the date and time you followed another person on Twitter, and vice versa! Who followed the other first?',
      },
      'emoji-mood': {
        description: 'What are the emojis you tweet the most? 🤖',
        longDescription: 'Thanks to the Emoji Mood, you will discover which emotions you have been tweeting the most recently... Would you be willing to bet on your TOP 3?',
      },
      'new-years-kiss': {
        description: 'Who are you going to kiss this year under the mistletoe? 😘',
        longDescription: 'We keep the algorithm of this feature secret. All we can say is that you will kiss someone at midnight!',
      },

    },

  },

  /* Tools */
  _tl: {

    list: {

      'id-username-converter': { description: 'Convert IDs to usernames and vice versa in real time.' },

      'welcome-message-editor': { description: 'Manage your Welcome Messages automatically displayed when someone wants to send you a private message.' },

      'deep-link-generator': { description: 'Create custom links to your private messages.' },

      'friends-followers-manager': { description: 'View and manage your following and followers easily and quickly.' },

    },

  },

  /* Pages */
  _pg: {

    /* Welcome page */
    welcome: {
      title: 'Welcome',
      welcomeToAffinitweet: 'Welcome to Affinitweet&nbsp;&nbsp;🎉',
      helloYou: 'Hello {username}&nbsp;&nbsp;😊',
      proudToWelcomeYou: 'Hi {username}, we are delighted to make your acquaintance and happy to welcome you among our more than 10 million users!',
      onboardingCreation: 'We are delighted to have you back with us! We created this little onboarding to make sure you know everything before everyone else...',
      next: 'Next',
      littleQuestion: 'Quick question...',
      doYouWantToFollowUs: 'We update Affinitweet regularly, do you want to follow us on Twitter to find out when new features will be available?',
      iWantToFollowYou: 'I want to follow you 😊',
      iDontWantToFollowYou: 'No thanks, I\'m good for now!',
      great: 'Great&nbsp;&nbsp;🥰',
      doYouWantToEnableNotifications: 'So, while you\'re at it, do you want to be notified of our tweets so you can be the first to test our new features?',
      iWantToBeNotified: 'I also want to be notified 😇',
      iDontWantToBeNotified: 'No, I just want the tweets!',
      noProblem: 'No problem&nbsp;&nbsp;😉',
      noProblemDescription: 'After all you\'re right, we hardly know each other! Maybe next time then, we hope you\'ll have fun on Affinitweet 💜',
      nice: 'Nice&nbsp;&nbsp;🤗',
      niceDescription: 'Hop... hop... and hop!<br />That\'s it, you\'re now following us on Twitter! Thanks a lot and have fun on Affinitweet 💜',
      awesome: 'Awesome&nbsp;&nbsp;😍',
      awesomeDescription: 'Hop... hop... and hop!<br /><br />That\'s it, you\'re now following us on Twitter and notifications have been enabled! Thanks a lot and have fun on Affinitweet 💜',
      uhoh: 'Uh oh... 😕',
      uhohDescription: 'Twitter, you\'ve got a problem...<br />Unfortunately Twitter isn\'t able to make you follow us at the moment. Please <u>click on the follow button</u> to do it 😊',
      letsGo: 'Let\'s go!',
    },

    /* Home page */
    index: {
      title: 'Home',
      description: 'Your Twitter account, more fun 😎 and more pro 🧑‍💻',
      titleH1: 'Your Twitter account,',
      titleH1s: 'more {fun} {emojiFun} more {pro} {emojiPro}',
      fun: 'fun',
      pro: 'pro',
      titleH2: 'Rediscover your Twitter account through dozens of exclusive features and tools to manage your account like a pro.',
      heresWhyAffinitweetIsNumberOne: "Here's why Affinitweet is the 1{sup} choice",
      sup: 'st',
      forALotOfUsers: 'for more than 10 million users worldwide',
      generatedResults: 'Beautiful generated results',
      generatedResultsDescription: 'Affinitweet is known for their very beautiful generated pictures, we are using the best tools for your results.',
      userConsentPrivacy: 'User consent & privacy',
      userConsentPrivacyDescription: 'Everything we do on Affinitweet with your data is explained in our privacy policy, no surprise, no auto-follow or auto-tweet.',
      worldFamousLeader: 'World famous leader',
      worldFamousLeaderDescription: 'Affinitweet opened in february 2015 and more than 10 million users use our services, everywhere in the world.',
      fastRealTimeResults: 'Fast and real-time results',
      fastRealTimeResultsDescription: "We built Affinitweet on the last web technologies, so it's as fast as possible with real-time on feature pages.",
      noAdsNoVirus: 'No intrusive ads, no virus',
      noAdsNoVirusDescription: "Affinitweet has been created just for fun, there's no virus and only 2 ads on the entire website (no popups, no redirects).",
      multilingualOpen: 'Multilingual & open',
      multilingualOpenDescription: 'Affinitweet is available in several different languages and everyone can contribute and add their own.',
      new: 'New',
      proTools: 'Professional tools',
      toManageYourTwitterAsAPro: 'to manage your Twitter account like a pro',
      discoverOurTools: 'Discover our tools',
      whatOurUsersSaid: 'What people say about us',
      ifYouNeedMoreTrust: 'if it takes more people and opinions to convince you',
      funFeatures: 'Entertaining features',
      unlimitedAndFree: 'interesting or fun, free and without limits',
      totalUsers: '10 million',
      totalUsersDescription: 'Users trust us and use our services',
      monthlyUsers: '400 000',
      monthlyUsersDescription: 'Unique users which come back in average each month',
      totalFeatures: '36 million',
      totalFeaturesDoneDescription: 'Features done since our opening in 2015',
      ourFeatures: 'Our features',
      seeDetailedList: 'See detailed list',
      getInTouch: 'Get in touch!',
      getInTouchP1: 'We are available at any time on our Twitter account {twitterName}.',
      getInTouchP2: 'Follow us and be notified about updates and upcoming things!',
      getInTouchP3: 'Feel free to send us a tweet or direct message if you have any question, suggestion or bug.',
      getInTouchP4: 'For commercial purpose, you can contact us by email, see our {pageName} page.',
    },

    /* User profile page */
    profile: {
      title: 'Profile',
      description: 'Account, settings and history of your profile.',
      joinBeta: 'Join the Beta program to test our features before they get released to public!',
      betaTerms: 'The Beta program is free of charge. Some features might not work and can be modified at anytime until they get published.',
      applyForFree: 'Apply for free',
      noThanks: 'No, thanks',
      profile: 'Profile',
      history: 'History',
      preferences: 'Preferences',
      language: 'Language',
      by: 'by',
      addLanguage: 'Add language...',
      contributeOnGitHub: 'contribute on GitHub',
      account: 'Account',
      followers: 'Followers',
      following: 'Following',
      noHistory: 'No history data.',
      autoTweet: 'Tweet results',
      autoTweetDescription: 'Check this option to automatically tweet your results. A tweet will be published once results are ready, no more.',
      saveResults: 'Save results',
      saveResultsDescription: 'Check this option to save your results in history (feature name + image + time). By default, we do not store your results.',
      emojis: 'Emojis pack',
      iOSemojis: 'iOS (Apple)',
      iOSemojisDescription: 'Your results will be generated with iOS Emojis.',
      androidEmojis: 'Android (Google)',
      androidEmojisDescription: 'Your results will be generated with Android Emojis.',
      clearHistory: 'Clear history',
      clearHistoryDescription: 'Clear your Affinitweet results history.',
      deleteAccount: 'Delete account',
      deleteAccountDescription: 'Delete your Affinitweet account, everything will be lost.',
      show: 'view',
      showMore: 'Show more...',
      saved: 'Saved',
    },

    /* Feature page */
    feature: {
      login: 'Log in to continue...',
      startFeature: "Let's go!",
      betaFeature: 'This feature is currently in beta and is available for users being part of the Beta program only. You can apply for this program if you want to test this feature.',
      applyForFree: 'Apply for free',
      results: "Here's your results!",
      tweetResults: 'Tweet results',
      tweetingResults: 'Tweeting...',
      requireAutoTweetDescription: "Do you want to enable auto-tweet results? You'll be able to deactivate this option from your profile.",
      yesEnable: 'Yes, enable',
      no: 'No',
      retry: 'Retry!',
      doYouWantToKnowMore: 'Do you want to learn more about your Twitter account?',
      discoverOtherFeatures: 'Discover more features',
    },

    /* Features listing page */
    features: {
      title: 'Features',
      description: 'Discover all our features to know everything about your Twitter account.',
      ourFeatures: "Here's a list of all our features {theyAreAllFree} you can try in no time that generate an image based on your Twitter account! If you're looking for a particular feature, you can use the search box below to see what we have to offer.",
      theyAreAllFree: 'entirely free',
      searchFeatures: 'Search features... (ex: Top Friends, Valentine...)',
      noFeatureFound: 'Unfortunately no feature matches this search... 😔',
      resetSearch: 'Reset search',
      letsGo: 'Let\'s go!',
    },

    /* Tool page */
    tool: {
      restrictedTool: 'This tool is in preview mode because it is reserved for Pro users. The data displayed are fake in order to simulate the use of the tool.',
      becomePro: 'Become Pro',
    },

    /* Tools listing page */
    tools: {
      title: 'Tools',
      description: "Here's a list of all our tools to improve the management of your Twitter account in various ways. These tools are part of {affinitweetPro}, a one-time purchase that gives you access to all these tools and more, forever.",
    },

    /* Beta program page */
    'beta-program': {
      title: 'Beta program',
      description: 'Apply to the Beta program for free and try our beta features before they get released to the public!',
      betaProgramDescription: "The Beta program has been created to test new features before they get released to the public to be sure that they're working as expected. By being part of this program, you will be able to test them.",
      currentBetaFeatures: 'There\'s currently {amount} {features} in the Beta program:',
      noCurrentBetaFeatures: 'There\'s currently no feature in the Beta program, but more are coming soon!',
      fewThingsToKnow: 'Few things to know about the Beta program:',
      li1: "It's 100% free of charge",
      li2: "There's a limited number of places",
      li3: 'You can leave it when you want',
      li4: 'Dedicated & priority support on Twitter by DM',
      li5: 'Beta features might not work as expected',
      li6: 'Beta features can change at anytime',
      thanksForInterest: 'Thank you for your interest regarding the Beta program 💜',
      alreadyApplied: "You're already in the Beta program,<br />thank you so much for your interest 💜",
      leaveBetaProgram: 'Leave the Beta program',
      leavingTerms: "If you leave the Beta Program, you may not be able to apply again if there's no available places.",
      placesAvailable: '500 places available! 🎟',
      proPlace: 'Here\'s your privileged place 👑',
      accountEligible: 'Your account is eligible to apply for the Beta program and few places are available!',
      yourEmailAddress: 'Your email address...',
      applyForFree: 'Apply for free',
      applyTerms: 'By applying to the Beta program, you agree to receive notification & promotion emails (1 per week maximum).',
      noPlaceAvailable: 'No place available 😕',
      betaProgramFull: "Unfortunately, the Beta program is full and we can't give free access at this time, but you can still try to earn an access by using the methods in the next block!",
      keepUpdated: 'We will let you know when new free access will be available on {ourTwitterAccount}.',
      ourTwitterAccount: 'our Twitter Account',
      or: 'or',
      earnYourAccess: 'Earn your access! 🎁',
      writeReview: '#1 — Write a review about us {onTrustpilot} and send us its link on our Twitter account by DM, we will then give you an access.',
      onTrustpilot: 'on Trustpilot',
      winContest: 'or #2 — Participate in our contests on {ourTwitterAccount} to win an access, follow us and enable notifications to keep updated.',
      randomDraws: 'Each of these contests ends with a random draw made on {pickaw}, so everyone have a chance to win.',
      welcomeToTheBetaProgram: 'Welcome to the Beta program! You can now test our Beta features 😊',
      seeYouSoonBetaProgram: 'Thanks for being part of the Beta program, can\'t wait to see you soon!',
    },

    pro: {
      title: 'Affinitweet Pro',
      description: 'Access exclusive tools and much more with Affinitweet Pro! 👑',
      alreadyLookedLikeAPro: "You already looked like a Pro, but now it's official.",
      welcomeHome: 'Welcome home, {username}',
      thanksForYourTrust: 'Thank you very much for your purchase and your trust {username} !',
      accessToOurBestTools: 'You now have access to our {bestTools} and much more, so enjoy',
      bestTools: 'best tools',
      couponExpireIn: 'Expire {expireIn}',
      heresACoupon: "Here's a discount code you can share with a friend to {saveMoney} on their Affinitweet Pro (or you can use it for another Twitter account you own 😌). Fantastic, right?",
      saveMoney: 'save 20%',
      shareYourCoupon: 'But hurry up! This code is unique and is {availableSevenDays} ! 🔥',
      availableSevenDays: 'available only 7 days after your purchase',
      whatIsAffinitweetPro: 'Affinitweet Pro is an offer to meet the high demand for new features for more professional needs, in the form of {uniquePurchase}.',
      uniquePurchase: 'one-time purchase valid for life: no subscription or renewal',
      newToolsWillCome: 'Many tools are already present and new ones are under development and will continue to be developed as time goes by. By becoming a Pro, here are the advantages you will be able to enjoy:',
      proAdvantages: {
        proTools: 'Access to our Pro tools',
        proToolsDescription: 'Take advantage of all the tools we offer, and those to come.',
        betaProgram: 'Privileged access to the Beta program',
        betaProgramDescription: 'Test future features and tools in development before anyone else.',
        removedAds: 'Advertisement removal',
        removedAdsDescription: 'Navigate much faster and easier on Affinitweet without ads.',
        priorityQueue: 'Priority queue',
        priorityQueueDescription: 'Save time and generate your results in priority during busy periods.',
        unlimitedHistory: 'Unlimited and detailed history',
        unlimitedHistoryDescription: 'Preserves the results of the features without any time limit.',
        thankYouPage: 'Thank you page',
        thankYouPageDescription: "Appearance on the thank you page, because we can't thank you enough.",
      },
      resetPurchase: 'Reset my purchase',
      resetPurchaseNotice: 'By leaving Affinitweet Pro, you will lose access to your benefits. You will be able to re-purchase at any time without any problem.',
      uniquePurchaseLifetimeAccess: 'One-time purchase, life-time access',
      satisfiedOrRefundedUnder7Days: 'Satisfied or refunded under 7 days',
      loginToBecomePro: 'Log in to become Pro',
      becomePro: 'Become Pro',
      contactUs: 'Contact us',
      orVerified: 'or verified',
      seeYouSoon: 'Thanks for being part of the Pro users, do not hesitate to come back later 😊',
    },

    'thank-you': {
      title: 'Thank you',
      description: 'This page lists all the users who support us through their {affinitweetPro} purchase. There are currently {number} and we wanted to thank each of them once again publicly 💜',
      searchPlaceholder: 'Search an awesome user 😍',
    },

    /* Legal page */
    legal: {
      title: 'Legal',
      description: 'Information about us and cookies.',
      intro: 'In accordance with Article 6 of the law n° 2004-575 of 21 June 2004 on trust in the digital economy, users of the site {site} are informed of the identity of the various parties involved in its implementation and monitoring:',
      owner: 'Owner',
      publisher: 'Publication manager',
      publisherText: 'The person responsible for publication is a natural person.',
      host: 'Host',
      requestAddress: 'Full address available on request by email at {email}.',
      warningCookies: 'About cookies',
      p1: 'A cookie is a small text file sent to your browser via the website you are viewing. With this cookie, information about your visit is stored on the website, such as your preferred language and other settings. This may facilitate your next visit to this site and make it more useful to you. Cookies play an important role. Without cookies, using the Web could be much more frustrating.',
      t1: 'What is the applicable legal frame?',
      p2: "In amending Article 5(3) of Directive 2002/58/EC by adopting Directive 2009/136/EC, the European legislator laid down the principle that the storage of information on a user's equipment or access to information already stored should only be carried out with the user's prior consent, unless these actions are strictly necessary for the provider to deliver a service expressly requested by the user. Article 32-II of the law of 6 January 1978 takes over this principle.",
      t2: 'This site uses cookies for the following purposes:',
      'l1-1': 'To help us recognize your browser and to save the preferences you have set in your previous visits to this site',
      'l1-2': 'To help us measure and study the effectiveness of our online interactive content, features, advertising and other communications',
      'l1-3': 'To monitor the analytical data on the site, the use made of the site by users and to improve the services and content of this site.',
      t3: 'How do I delete cookies linked to my browser?',
      p3: "You can choose to disable cookies in your browser at any time by following the instructions provided in your browser's help files. You can also set your cookies directly in your browser settings:",
    },

    /* Terms of service page */
    terms: {
      title: 'Terms of service',
      description: 'Consult our general terms and conditions of use.',
      h1: 'Terms',
      p1: 'By accessing the website at {url}, you are agreeing to be bound by these terms of service, all applicable laws and regulations, and agree that you are responsible for compliance with any applicable local laws. If you do not agree with any of these terms, you are prohibited from using or accessing this site. The materials contained in this website are protected by applicable copyright and trademark law.',
      h2: 'Use Licence',
      'l1-1': "Permission is granted to temporarily download one copy of the materials (information or software) on Affinitweet's website for personal, non-commercial transitory viewing only. This is the grant of a license, not a transfer of title, and under this license you may not:",
      'l2-1': 'modify or copy the materials;',
      'l2-2': 'use the materials for any commercial purpose, or for any public display (commercial or non-commercial);',
      'l2-3': "attempt to decompile or reverse engineer any software contained on Affinitweet's website;",
      'l2-4': 'remove any copyright or other proprietary notations from the materials; or',
      'l2-5': 'transfer the materials to another person or "mirror" the materials on any other server.',
      'l1-2': 'This license shall automatically terminate if you violate any of these restrictions and may be terminated by Affinitweet at any time. Upon terminating your viewing of these materials or upon the termination of this license, you must destroy any downloaded materials in your possession whether in electronic or printed format.',
      h3: 'Disclaimer',
      'l3-1': "The materials on Affinitweet's website are provided on an 'as is' basis. Affinitweet makes no warranties, expressed or implied, and hereby disclaims and negates all other warranties including, without limitation, implied warranties or conditions of merchantability, fitness for a particular purpose, or non-infringement of intellectual property or other violation of rights.",
      'l3-2': 'Further, Affinitweet does not warrant or make any representations concerning the accuracy, likely results, or reliability of the use of the materials on its website or otherwise relating to such materials or on any sites linked to this site.',
      h4: 'Limitations',
      p2: "In no event shall Affinitweet or its suppliers be liable for any damages (including, without limitation, damages for loss of data or profit, or due to business interruption) arising out of the use or inability to use the materials on Affinitweet's website, even if Affinitweet or a Affinitweet authorized representative has been notified orally or in writing of the possibility of such damage. Because some jurisdictions do not allow limitations on implied warranties, or limitations of liability for consequential or incidental damages, these limitations may not apply to you.",
      h5: 'Accuracy of materials',
      p3: "The materials appearing on Affinitweet's website could include technical, typographical, or photographic errors. Affinitweet does not warrant that any of the materials on its website are accurate, complete or current. Affinitweet may make changes to the materials contained on its website at any time without notice. However Affinitweet does not make any commitment to update the materials.",
      h6: 'Links',
      p4: "Affinitweet has not reviewed all of the sites linked to its website and is not responsible for the contents of any such linked site. The inclusion of any link does not imply endorsement by Affinitweet of the site. Use of any such linked website is at the user's own risk.",
      h7: 'Modifications',
      p5: 'Affinitweet may revise these terms of service for its website at any time without notice. By using this website you are agreeing to be bound by the then current version of these terms of service.',
      h8: 'Governing Law',
      p6: 'These terms and conditions are governed by and construed in accordance with the laws of France and you irrevocably submit to the exclusive jurisdiction of the courts in that State or location.',
      'h9-1': 'Terms of sale',
      p7: "Affinitweet Pro is sold as a one-time purchase, at different prices depending on the influence of the user's Twitter account. When the customer's Twitter account gains influence and exceeds a new threshold, no extra charge is made or requested.",
      p8: 'Under certain conditions, the user may not be able to proceed with an online purchase and may need to contact the Affinitweet team to receive the full benefits of Affinitweet Pro.',
      p9: 'Prices displayed may fluctuate at any time, without the customer being able to request a refund for the difference.',
      'h9-2': 'Refund policy',
      p10: 'Affinitweet offers a 7-day "money back" policy, starting from the date of purchase, only if: (1) the promotional code generated at the end of the purchase has not been used ; and (2) the user has not received a refund in the past.',
      p11: "If these conditions are met, the customer can make a refund request by sending an email to {email} which will be processed and accepted as soon as possible. The refund will be effective on the customer's bank account within 5 to 10 days from the date of processing the request, and will result in the immediate cancellation of all Affinitweet Pro benefits.",
      p12: 'On the contrary, if these conditions aren\'t met, Affinitweet reserves the right not to grant the refund request. In the same way, no refund or transfer of benefits will take place, even after the 7 day period, if the Twitter account becomes unusable in any way (suspended by Twitter, change of account, etc...): Affinitweet Pro is associated with the Twitter account on which the purchase was made. The customer will then have to log in with the new account and make a new purchase.',
      p13: 'In very rare cases, some tools might not work (fully or partially) if the user has a private Twitter account with more than 75000 followers or followings. The customer will not be able to claim a refund outside of the 7 day period.',
    },

    /* Data and privacy page */
    privacy: {
      title: 'Data and privacy',
      description: 'Information on how we retrieve, analyze and store your data.',
      intro: 'We take the privacy of data very seriously and in the course of our business, we want to inform our users about what we do with it. You will find below all the necessary information concerning the storage and processing of this data. Information about cookies is also available on {thatPage}.',
      storage: 'Storage',
      personalData: 'Personal data',
      p1: 'When you log into Affinitweet, we collect the information from your Twitter profile that we need in order to offer you our services. Among this information, we store your:',
      'l1-1': 'unique Twitter ID',
      'l1-2': 'username (@)',
      'l1-3': 'name',
      'l1-4': 'authentication token',
      'l1-5': 'authentication token secret',
      'l1-6': 'language',
      p2: 'The other information you can see on your profile is temporarily stored in your session, just log out to delete it.',
      i1: 'Information: these data can be deleted in their entirety and immediately on simply clicking on {button} at the bottom of {yourProfile}.',
      results: 'Results',
      p3: 'By default, Affinitweet does not store the results of what you do. However, you can activate this option to have a history of your results in your profile. Among this information, we store:',
      'l2-1': 'the user to whom the result belongs',
      'l2-2': 'the name of the feature',
      'l2-3': 'the timestamp of the result',
      i2: 'Information: these data can be deleted in their entirety and immediately by simply clicking on {button} at the bottom of {yourProfile}.',
      computing: 'Processing',
      p4: 'When you perform the various features present on the site, we make calls to the Twitter API with your previously stored tokens.',
      i3: 'Information: we use your tokens to be able being as accurate as possible in our results. Thus, if you follow one or more users with a protected account for example, we will be able to include them in the results if necessary.',
      p5: "Here's what we can be led to get:",
      'l3-1': 'your feed',
      'l3-2': 'your tweets/retweets',
      'l3-3': 'your mentions',
      'l3-4': 'your followers',
      'l3-5': 'your following',
      p6: 'This information is only collected and processed, we do not store it.',
      publish: 'Publication',
      p7: 'When you log in to Affinitweet, we ask for basic read access to your account and write access. We will not carry out any action without your express request by activating an option from the site.',
      i4: 'Information: you can revoke the access you gave us when you logged in at any time from your {yourTwitterProfile}.',
      autoTweet: 'Automatic tweet',
      p8: 'In order to be able to use certain features, we may ask you to enable the automatic tweet option for results. If you agree to enable this option, a tweet will be published for each result with the generated image.',
      i5: 'Information: you can deactivate this option at any time from {yourProfile} in the {button} section.',
      question: 'Any questions?',
      p9: 'If you have any questions about Affinitweet, please do not hesitate to contact us via Twitter or email, we will be happy to answer you!',
      thatPage: 'this page',
      yourProfile: 'your profile',
      yourTwitterProfile: 'your Twitter profile',
    },

  },

  /* Errors */
  _er: {
    back: 'Back',
    reload: 'Reload',
    400: 'Bad request 🤨',
    401: 'Unauthenticated 🙄',
    402: 'Payment required 😬',
    403: 'Forbidden 😕',
    404: 'This page could not be found 😢',
    405: 'Method not allowed 🧐',
    500: 'The server returned an error 😧',
    detailed400: 'It seems there is a problem in the request.<br/>Retry again or contact us for more information.',
    detailed401: 'You must be logged in to access this page.<br/>Log in and then retry.',
    detailed402: 'You cannot access this page because it requires payment.',
    detailed403: "You don't have the rights to access this page.<br/>Please refer to the owner of the team.",
    detailed404: "It seems that the page you are looking for does not exist or no longer exists. Please contact us if it's a dead link.",
    detailed405: 'The method used to access this page is not allowed.',
    detailed500: 'The server has returned an error. Try to reload the page in a few moments.',
    cooldown: 'This feature have a %{cooldown} seconds cooldown. Please retry in:',
    unknown: 'An error has occured. Our team has been notified.',
    unknownFeature: 'Unknown feature.',
    unavailableFeature: 'Unavailable feature.',
    betaFeature: "You can't use beta features until you're appart of the Beta program.",
    invalidEmail: 'Email is invalid.',
    selfUsername: 'Type a different username than yourself.',
    badUsername: 'Bad username.',
    notEnoughData: 'Not enough tweets to analyze.',
    errorWhileRendering: 'Error while generating image.',
    accountProtected: "You can't use this feature while your account is protected.",
    targetAccountProtectedAndNotFollowing: "You can't use this feature because the targeted user is protected and not following you.",
    refreshPage: 'Please refresh the page.',
    timeout: 'Timeout exceeded.',
    twitterError: 'Twitter returned an error:',
    twitterErrors: {
      32: 'Could not authenticate you.',
      34: 'Sorry, that page does not exist.',
      50: 'User not found.',
      63: 'User has been suspended.',
      64: 'Your account is suspended and is not permitted to access this feature.',
      87: 'Client is not permitted to perform this action.',
      88: 'Rate limit exceeded. Retry in 15 minutes',
      89: 'Invalid or expired token. Please reconnect.',
      99: 'Unable to verify your credentials.',
      130: 'Over capacity.',
      131: 'Internal error.',
      135: 'Could not authenticate you.',
      144: 'No status found with that ID.',
      179: 'Sorry, you are not authorized to see this status.',
      185: 'User is over daily status update limit.',
      186: 'Tweet needs to be a bit shorter.',
      187: 'Status is a duplicate.',
      220: 'Your credentials do not allow access to this resource.',
      261: 'Application cannot perform write actions.',
      326: 'To protect our users from spam and other malicious activity, this account is temporarily locked.',
    },
  },

}
