export default {

  _st: {
    received: 'Żądanie przyjęte przez serwer...',
    starting: 'Rozpoczynanie...',
    fetchingData: 'Ładowanie danych...',
    fetchingTweets: 'Ładowanie tweetów...',
    computingData: 'Przetwarzanie danych...',
    generatingImage: 'Generowanie grafiki...',
    uploadingMedia: 'Przesyłanie grafiki...',
    publishingTweet: 'Publikowanie tweeta...',
    savingResults: 'Zapisywanie wyników...',
  },

  _ft: {
    'first-to-follow': {
      youAreNotFollowing: 'Nie obserwujesz {user}...',
      notFollowingYou: '{user} nie obserwuje cię...',
      youFollowed: 'Obserwujesz {user} od: ',
      followedYou: '{user} obserwuje cię od: ',
      dateFormat: '{day}/{month}/{year}, {hour}:{minute}:{second}',
      dateFormat2: '{day}/{month}/{year}, {hour}h',
    },
    friendships: {
      average: 'Zgodność znajomości na poziomie',
      following: 'Obserwujesz tego użytkownika',
      'not-following': 'Nie obserwujesz tego użytkownika',
      followed_by: 'Ten użytkownik cię obserwuje',
      'not-followed_by': 'Ten użytkownik cię nie obserwuje',
      notifications_enabled: 'Otrzymujesz powiadomienia o tweetach tego użytkownika',
      'not-notifications_enabled': 'Nie otrzymujesz powiadomień o tweetach tego użytkownika',
      blocking: 'Ten użytkownik został przez ciebie zablokowany',
      'not-blocking': 'Ten użytkownik nie został przez ciebie zablokowany',
      blocked_by: 'Ten użytkownik cię zablokował',
      'not-blocked_by': 'Ten użytkownik cię nie zablokował',
      muting: 'Ten użytkownik został przez ciebie wyciszony',
      'not-muting': 'Ten użytkownik nie został przez ciebie wyciszony',
      want_retweets: 'Widzisz retweety tego użytkownika',
      'not-want_retweets': 'Nie widzisz retweetów tego użytkownika',
      marked_spam: 'Ten użytkownik został przez ciebie oznaczony jako spam',
      'not-marked_spam': 'Ten użytkownik nie został przez ciebie oznaczony jako spam',
    },
    'tweet-rate': {
      average: '{user} publikuje średnio...',
      tweetsPerDay: '{count} tweetów dziennie',
    },
    'common-friends': {
      friendsRemaining: '... oraz {count} innych znajomych!',
      noFriends: 'Brak wspólnych znajomych...',
      commonFriends: 'Mam {count} wspólnych znajomych z {user}!',
      noCommonFriends: 'Nie mam wspólnych znajomych z {user}...',
    },
    valentine: 'Twoją walentynką w {year} roku jest',
    'stolen-kiss': 'Buziaka wysyła ci',
    'hidden-twin': 'Twoim tajemniczym bliźniakiem jest',
    'secret-crush': 'Sekretnie podkochujesz się w użytkowniku',
    'may-day': 'Daję konwalię majową 💐 użytkownikowi',
    'halloween-duo': 'W tym roku świętujesz Halloween z użytkownikiem',
    'new-years-kiss': "My New Year's Kiss is",
  },

  _tw: {
    'first-to-follow': '#Affinitweet First To Follow\n{text}\nvia https://affinitweet.com/first-to-follow',
    friendships: '#Affinitweet Friendships\n{text}\nvia https://affinitweet.com/friendships',
    'top-friends': '#Affinitweet Top Friends\n{users}\nvia https://affinitweet.com/top-friends',
    'famous-followers': '#Affinitweet Famous Followers\n{users}\nvia https://affinitweet.com/famous-followers',
    'common-friends': '#Affinitweet Common Friends\n{text}\nhttps://affinitweet.com/common-friends',
    'tweet-rate': '#Affinitweet Tweet Rate\n\nhttps://affinitweet.com/tweet-rate',
    'emoji-mood': '#Affinitweet Emoji Mood\n{emojis}\nprzez https://affinitweet.com/emoji-mood',
    valentine: '#Affinitweet Valentine\nW tym roku jesteś moją walentynką, {user}! ❤️\nKto będzie twoją?\nhttps://affinitweet.com/valentine',
    'secret-crush': '#Affinitweet Secret Crush\nPodkochujesz się sekretnie w {user}! 😳\nKto podkochuje się w tobie?\nhttps://affinitweet.com/secret-crush',
    'hidden-twin': '#Affinitweet Hidden Twin\n{user} jest moim tajemniczym bliźniakiem 😱\nZnajdź swojego!\nhttps://affinitweet.com/hidden-twin',
    'stolen-kiss': '#Affinitweet Stolen Kiss\n{user} wysyła ci buziaka... 😏\nA kogo ty pocałujesz?\nhttps://affinitweet.com/stolen-kiss',
    'may-day': '#Affinitweet May Day\n{user}, daję ci w prezencie konwalie majowe! 💐\nKomu podarujesz swój bukiet?\nhttps://affinitweet.com/may-day',
    'halloween-duo': '#Affinitweet Halloween Duo\nW tym roku nawet nie muszę się przebierać, bo straszy ze mną {user}! 🎃👻\nZnajdź swojego strasznego partnera!\nhttps://affinitweet.com/halloween-duo',
    'new-years-kiss': "#Affinitweet New Year's Kiss\nI'm preparing my best last year kiss and first of the next year {user} 😘💕\nAnd you, who will you kiss at midnight?\nvia https://affinitweet.com/christmas-gift",
  },

}
