export default {

  /* Steps */
  _st: {
    received: 'Richiesta ricevuta dal server...',
    starting: 'Iniziando...',
    fetchingData: 'Recupero dati...',
    fetchingTweets: 'Recupero tweet...',
    computingData: 'Calcolo dei dati...',
    generatingImage: 'Generazione di immagine...',
    uploadingMedia: 'Caricamento immagine...',
    publishingTweet: 'Tweet Pubblicato...',
    savingResults: 'Salvo i risultati...',
  },

  /* Features */
  _ft: {
    'twitter-activity': {
      basedOnLastDays: 'Sulla base degli ultimi {days} giorni...',
      countingTweets: '... e conteggio {count} tweets:',
      interactionsReceived: 'Interazioni ricevute',
      last30Days: '*: ultimi 30 giorni',
      tweetingHours: 'Tweeting nelle ultime ore',
      tweetRepartition: 'Tweet distribuiti',
    },
    'first-follower': {
      yourFirstFollowerIs: 'Il tuo primo seguace è',
      dateFormat: 'on {month}/{day}/{year} at {hour}:{minute}:{second}',
    },
    'first-following': {
      yourFirstFollowingIs: 'Il tuo primo seguito è',
      dateFormat: 'on {month}/{day}/{year} at {hour}:{minute}:{second}',
    },
    'first-to-follow': {
      youAreNotFollowing: "Non stai seguendo {user}...",
      notFollowingYou: '{user} Non ti sta seguendo...',
      youFollowed: 'Hai seguito {user}: ',
      followedYou: '{user} followed you: ',
      dateFormat: 'on {month}/{day}/{year} at {hour}:{minute}:{second}',
      dateFormat2: 'on {month}/{day}/{year} at {hour}h',
    },
    friendships: {
      average: 'Media delle amicizie di',
      following: 'Tu\'li stanno seguendo',
      'not-following': "You're not following them",
      followed_by: 'Loro\' ti stanno seguendo',
      'not-followed_by': "Non ti stanno seguendo",
      notifications_enabled: 'Ricevi una notifica quando twittano',
      'not-notifications_enabled': "Non sei avvisato quando twittano",
      blocking: 'Li hai bloccati',
      'not-blocking': "Non li hai bloccati",
      blocked_by: 'Ti hanno bloccato',
      'not-blocked_by': "Non ti hanno bloccato",
      muting: 'Tu hai mutato',
      'not-muting': "Non li hai mutati",
      want_retweets: 'Vedi i loro retweet',
      'not-want_retweets': "Non vedi i loro retweet",
      marked_spam: 'Li hai contrassegnati come spam',
      'not-marked_spam': "Non li hai contrasegnati come spam",
    },
    'tweet-rate': {
      average: '{user} Media di tweet...',
      tweetsPerDay: '{count} Volte al giorno',
    },
    'common-friends': {
      friendsRemaining: '... E {count} Altri amici!',
      noFriends: 'Nessun amico comune...',
      commonFriends: 'Io ho {count} amici in comune con {user}!',
      noCommonFriends: 'Io non ho amici in comune con {user}...',
    },
    valentine: 'Il tuo San Valentino {year} È',
    'stolen-kiss': 'Il tuo bacio rubato è',
    'hidden-twin': 'Il tuo gemello nascosto è',
    'secret-crush': 'La tua cotta segreta è',
    'may-day': 'I give a Lily-of-the-Valley 💐 to',
    'halloween-duo': 'Il tuo duo di Halloween è',
    'new-years-kiss': "Il bacio del mio nuovo anno è",
  },

  /* Tweet content */
  _tw: {
    'first-to-follow': '{text}',
    friendships: '{text}',
    'top-friends': '{users}',
    'famous-followers': '{users}',
    'common-friends': '{text}',
    'tweet-rate': '{text}',
    'emoji-mood': '{emojis}',
    valentine: "Quest'anno sei mio {user}! ❤️\nE tu, che sarai tuo?",
    'twitter-activity': "Ecco le statistiche del mio account nei passati {days} giorni. Le tue migliori interazioni?",
    'first-follower': 'Ho appena scoperto il mio primo follower su Twitter, è {user} E loro mi ha seguito {date}!\nChi è il tuo primo follower?',
    'first-following': 'Ho appena scoperto il mio primo seguito su Twitter, è {user} e lo seguito {date}!\n Il tuo primo seguito?',
    'secret-crush': '{user} Ti ama segretamente! 😳\nChi ti ama in segreto?',
    'hidden-twin': '{user} È il mio gemello nascosto 😱\nScopri chi è tuo!',
    'stolen-kiss': '{user} ti bacerebbe dietro un angolo... 😏\ne tu, a chi lo faresti?',
    'may-day': '{user}, Ti do il mio miglior bouquet di mughetto! 💐\nA chi darai il tuo?',
    'halloween-duo': "Non devo nemmeno vestirmi quest'anno per spaventarmi, sono con {user}! 🎃👻\nE tu, con chi spaventerai di più?",
    'new-years-kiss': "Sto preparando il mio miglior bacio l'anno scorso e il primo del prossimo anno {user} 😘💕\nE tu, che bacerai a mezzanotte?",
  },

}
