export default {

  /* Layouts */
  _lt: {

    default: {
      cookiesBanner: 'Usiamo i cookies 🍪 per offrirti un esperienza migliore possibile. Per continuare usare il sito accetta la policy dei cookies {button}',
      readMore: 'Leggi Altro...',
    },

  },

  /* Common */
  _cm: {
    lastRevision: 'Ultimo Aggiornamento:',
    contactUs: 'Contattaci Ora',
    followUs: 'Seguici',
    reviewUs: 'Recensiscici',
    close: 'Chiudi',
    cancel: 'Cancella',
  },

  /* Languages */
  _lg: {
    french: 'Francese',
    english: 'Inglese',
    polish: 'Polacco',
    spanish: 'Spagnolo',
    swedish: 'Svedese',
    turkish: 'Turko',
    indonesian: 'Indonesiano',
    portuguese: 'PPortoghese',
    simplifiedChinese: 'Cinese Semplificato',
    traditionalChinese: 'Cinese Tradizionale',
    dutch: 'Olandese',
    italy: 'Italiano'
  },

  /* Pluralization */
  _pl: {
    seconds: 'second | second | seconds',
    features: 'feature | feature | features',
  },

  /* Components */
  _cp: {

    /* Header component */
    header: {
      sidebarHint: 'Scopri tutte le novita clicando il menù 😉',
      logIn: 'Log in',
      myAccount: 'My account',
      switchAccount: 'Switch account',
      logout: 'Log out',
    },

    /* Footer component */
    footer: {
      madeWithLove: 'Affinitweet è una piattaforma di statistiche e intrattenimento basata su Twitter creata nel 2015 con ❤️ in Francia.',
      allRightsReserved: 'Tutti i Diritti Riservati.',
      about: 'About',
      changelog: 'Changelog',
      legal: 'Legal',
      partners: 'Partners',
    },

    stateButton: {
      hold: 'Tieni premuto per confermare',
      submit: 'Clicca per confermare',
      loading: 'Azione in corso...',
      cancel: 'Cancela',
    },

    clearHistory: {
      title: 'Pulisci la cronologia',
      description: 'Ripulendo la cronologia, tutte le informazioni e le immagini dei risultati attualmente salvati verranno eliminate.',
      description2: 'Non sarai in grado di vedere i tuoi risultati precedenti dopo questa pulizia, vuoi davvero eseguire questa azione?',
      holdButton: 'Tieni premuto per cancellare',
      loadingButton: 'Cancellazione cronologia...',
      successModal: 'La tua cronologia è stata cancellata.',
    },

    deleteAccount: {
      title: 'Eliminare il tuo account',
      description: 'Qualcosa è andato storto? Diccelo sul nostro account Twitter in modo che possiamo migliorare!',
      description2: 'Eliminando il tuo account, verranno eliminati tutti i dati su di te, inclusa la cronologia. Nessun dato verrà conservato e verrai automaticamente disconnesso da Affinitweet.',
      description3: 'Non sarai in grado di recuperare il tuo account corrente dopo questa cancellazione, vuoi davvero eseguire questa azione?',
      holdButton: 'Tieni premuto per eliminare',
      loadingButton: 'Eliminazione del tuo account in corso...',
      successModal: 'Il tuo account è stato eliminato.',
    },

  },

  /* Features */
  _ft: {

    new: 'Nuovo',
    popular: 'Popolare',
    real: 'Reale',
    fun: 'Divertente',

    list: {

      friendships: {
        description: 'Tutto quello che devi sapere sui collegamenti tra te e un utente! 🙌',
        longDescription: 'Grazie ad Amicizie saprai quanto sei amico di un altro utente a tua scelta: più pallini blu hai, più forti saranno i legami! Inserisci il nickname Twitter della persona prescelta e scopri le tue amicizie!',
      },
      'common-friends': {
        description: 'Scopri i tuoi amici in comune con un altro utente! 👥',
        longDescription: 'Gli amici comuni ti permettono di scoprire gli abbonamenti/amici che hai in comune con altre persone. Avete gli stessi gusti e quanto?',
      },
      'top-friends': {
        description: 'Scopri i tuoi migliori amici di Twitter negli ultimi tempi! 🤗',
        longDescription: 'I migliori amici ti permettono di sapere chi sono i tuoi migliori amici su Twitter. Stabiliamo una classifica analizzando le informazioni inviate e ricevute dal tuo account. Quindi li contiamo, li aggiungiamo e li ordiniamo per generare i tuoi migliori amici!',
      },
      'famous-followers': {
        description: 'Scopri le persone più popolari nei tuoi follower! 💅',
        longDescription: 'The Famous Followers ti consente di sapere quali persone hanno più follower tra i tuoi follower. Raccogliamo ciascuno dei tuoi follower e il loro numero di follower e li ordiniamo per generare i tuoi follower famosi!',
      },
      valentine: {
        description: 'Sappiamo chi sarà il tuo San Valentino... E tu? 💏',
        longDescription: 'Manteniamo segreto il nostro algoritmo per questa funzione. Tutto quello che possiamo dire è che stiamo cercando di attenerci alla realtà, il nostro San Valentino ti delizierà... ?',
      },
      'twitter-activity': {
        description: 'Scopri il riepilogo della tua attività e le tue statistiche su Twitter 📊',
        longDescription: 'Grazie a Twitter Activity, saprai quando twitti più spesso, quante interazioni (impressioni, retweet, Mi piace, risposte) hai in totale e la distribuzione dei tuoi tweet.',
      },
      'first-follower': {
        description: 'Scopri chi è la prima persona che ti ha seguito su Twitter 1️⃣',
        longDescription: 'Grazie al First Follower saprai chi è il tuo primo follower e quando ti ha seguito (o il più vecchio, perché se nel frattempo non sei stato seguito non possiamo saperlo).',
      },
      'first-following': {
        description: 'Scopri chi è la prima persona che hai seguito su Twitter 1️⃣',
        longDescription: 'Grazie al First Following, saprai chi è il tuo primo follower e quando lo hai seguito (o il più vecchio, perché se hai smesso di seguire persone nel frattempo, non possiamo saperlo).',
      },
      'secret-crush': {
        description: 'Qualcuno ti ama in segreto... e te lo nasconde... 😳',
        longDescription: 'Manteniamo segreto il nostro algoritmo per questa funzione. Tutto quello che possiamo dire è che la tua cotta segreta ti impressionerà, nel bene o nel male?',
      },
      'hidden-twin': {
        description: 'Sì, hai un gemello nascosto... chi diavolo è? 🤔',
        longDescription: 'Manteniamo segreto il nostro algoritmo per questa funzione. Tutto quello che possiamo dire è che il tuo gemello nascosto ti impressionerà, nel bene o nel male?',
      },
      'stolen-kiss': {
        description: 'Chi ti vuole rubare un bacio per strada? 💋',
        longDescription: 'Manteniamo segreto il nostro algoritmo per questa funzione. Tutto quello che possiamo dire è che il tuo bacio rubato ti impressionerà, nel bene o nel male?',
      },
      'may-day': {
        description: 'qual è il tuo miglior bouquet per questo anno?💐',
        longDescription: 'Manteniamo segreto il nostro algoritmo per questa funzione. Tutto quello che possiamo dire è che renderai qualcuno molto felice!',
      },
      'halloween-duo': {
        description: 'Con chi avrai più paura questo anno?? 🎃👻',
        longDescription: 'Manteniamo segreto il nostro algoritmo per questa funzione. Tutto quello che possiamo dire è che questo anno farai paura ad Halloween!',
      },
      'tweet-rate': {
        description: 'Confronta il tuo tasso di tweet con un altro utente! 📊',
        longDescription: 'Il Tweet Rate ti permette di conoscere il numero medio di tweet che pubblichi al giorno da quando ti sei registrato su Twitter e di confrontarti con un altro utente! Sei il più attivo?',
      },
      'first-to-follow': {
        description: 'Scopri quando segui un utente e viceversa! 😮',
        longDescription: 'Il First To Follow ti permette di scoprire le date e le ore in cui hai seguito un utente su Twitter e viceversa! Chi ha seguito per primo un altro utente?',
      },
      'emoji-mood': {
        description: 'Quali sono le emoji che twitti di più? 🤖',
        longDescription: 'Grazie alle Emoji Mood, scoprirai quali emozioni hai twittato più di recente... Scommetteresti sulla tua TOP 3?',
      },
      'new-years-kiss': {
        description: 'Chi bacerai questo anno sotto il vischio? 😘',
        longDescription: 'Manteniamo segreto il nostro algoritmo per questa funzione. Tutto quello che possiamo dire è che bacerai qualcuno a mezzanotte!',
      },

    },

  },

  /* Pages */
  _pg: {

    /* Welcome page */
    welcome: {
      title: 'Benvenuto',
      welcomeToAffinitweet: 'Benvenuto su Affinitweet&nbsp;&nbsp;🎉',
      helloYou: 'Ciao {username}&nbsp;&nbsp;😊',
      proudToWelcomeYou: 'Ciao {username}, siamo lieti di fare la tua conoscenza e felici di darti il ​​benvenuto tra i nostri oltre 6 milioni di utenti!',
      onboardingCreation: 'Siamo felici di riaverti con noi! Abbiamo creato questo piccolo onboarding per assicurarci che tu sappia tutto prima di tutti gli altri...',
      next: 'Il Prossimo',
      littleQuestion: 'Domanda Veloce...',
      doYouWantToFollowUs: 'Aggiorniamo regolarmente Affinitweet, vuoi seguirci su Twitter per scoprire quando saranno disponibili nuove funzionalità?',
      iWantToFollowYou: 'Voglio seguirti 😊',
      iDontWantToFollowYou: 'No grazie, per ora sto bene!',
      great: 'Grande&nbsp;&nbsp;🥰',
      doYouWantToEnableNotifications: 'Quindi, già che ci sei, vuoi essere avvisato dei tuoi tweet in modo da poter essere il primo a testare le nostre nuove funzionalità?',
      iWantToBeNotified: 'Voglio essere avvisato anche io 😇',
      iDontWantToBeNotified: 'No, voglio solo i tweet!',
      noProblem: 'Nessun Problema&nbsp;&nbsp;😉',
      noProblemDescription: 'In fondo hai ragione, ci conosciamo a malapena! Forse la prossima volta allora, speriamo che vi divertiate tutti su Affinitweet 💜',
      nice: 'Bello&nbsp;&nbsp;🤗',
      niceDescription: 'Hop... hop... and hop!<br /> Ecco, ora ci stai seguendo su Twitter! Grazie mille e buon divertimento su Affinitweet 💜',
      awesome: 'Awesome&nbsp;&nbsp;😍',
      awesomeDescription: 'Hop... hop... and hop!<br /> <br /> Questo è tutto, ora ci stai seguendo su Twitter e le notifiche sono state abilitate! Grazie mille e buon divertimento su Affinitweet 💜',
      uhoh: 'Uh oh... 😕',
      uhohDescription: 'Twitter, hai un problema...<br /> Purtroppo Twitter non è in grado di farti seguire da te al momento. Per favore <u>clicca sul pulsante segui</u> per farlo 😊',
      letsGo: 'Lascia andare!',
    },

    /* Home page */
    index: {
      title: 'Home',
      description: 'Il posto migliore per divertirti con i tuoi amici su Twitter! Controlla le tue statistiche e altro!',
      titleH1: 'Il posto migliore per divertirti con i tuoi amici su Twitter!',
      titleH2: 'Controlla le tue statistiche e altro!',
      highlights: 'Highlights',
      generatedResults: 'Bellissimi risultati generati',
      generatedResultsDescription: 'Affinitweet è noto per le sue bellissime immagini generate, stiamo utilizzando i migliori strumenti per i tuoi risultati.',
      userConsentPrivacy: 'Consenso della privacy utente',
      userConsentPrivacyDescription: 'Tutto ciò che facciamo su Affinitweet con i tuoi dati è spiegato nella nostra politica sulla privacy, nessuna sorpresa, nessun auto-follow o auto-tweet.',
      worldFamousLeader: 'World famous leader',
      worldFamousLeaderDescription: 'Affinitweet è stato aperto nel febbraio 2014 e più di due milioni di utenti utilizzano i nostri servizi, ovunque nel mondo.',
      fastRealTimeResults: 'Risultati veloci e in tempo reale',
      fastRealTimeResultsDescription: "Abbiamo costruito Affinitweet sulle ultime tecnologie web, quindi è il più veloce possibile con le pagine delle funzionalità in tempo reale.",
      noAdsNoVirus: 'Annunci non invadenti, nessun virus',
      noAdsNoVirusDescription: "Affinitweet è stato creato solo per divertimento, non ci sono virus e solo 2 annunci su tutto il sito web (nessun pop up, nessun reindirizzamento).",
      multilingualOpen: 'Multilingue e aperto',
      multilingualOpenDescription: 'Affinitweet è disponibile in diverse lingue e tutti possono contribuire e aggiungere il proprio.',
      trustpilotH1: "Controlla le recensioni dei nostri utenti su Trustpilot!",
      trustpilotH2: 'Siamo valutati {rate} dai nostri utenti, sarai il prossimo a recensirci?',
      trustpilotButton: 'Visualizza e invia una recensione',
      statistics: 'Statistiche',
      totalUsers: '7 milioni',
      totalUsersDescription: 'Gli utenti si fidano di noi e utilizzano i nostri servizi',
      monthlyUsers: '400 000',
      monthlyUsersDescription: 'Utenti unici che tornano in media ogni mese',
      totalFeatures: '20 milioni',
      totalFeaturesDoneDescription: 'Funzionalità realizzate dalla nostra apertura nel 2014',
      ourFeatures: 'Le nostre caratteristiche',
      seeDetailedList: 'Vedi elenco dettagliato',
      latestNews: 'Ultime notizie',
      getInTouch: 'Mettiti in contatto!',
      getInTouchP1: 'Siamo disponibili in qualsiasi momento sul nostro account Twitter {twitterName}.',
      getInTouchP2: 'Seguici e sarai informato sugli aggiornamenti e sulle cose imminenti!',
      getInTouchP3: 'Sentiti libero di inviarci un tweet o un messaggio diretto se hai domande, suggerimenti o bug.',
      getInTouchP4: 'Per scopi commerciali, puoi contattarci via e-mail, vedere il nostro {pageName} pagina.',
    },

    /* User profile page */
    profile: {
      title: 'Profilo',
      description: 'Account, impostazioni e cronologia del tuo profilo.',
      joinBeta: 'Unisciti al programma Beta per testare le nostre funzionalità prima che vengano rilasciate al pubblico!',
      betaTerms: 'Il programma Beta è gratuito. Alcune funzionalità potrebbero non funzionare e possono essere modificate in qualsiasi momento fino a quando non vengono pubblicate.',
      applyForFree: 'Candidati gratuitamente',
      noThanks: 'No, Grazie',
      profile: 'Profilo',
      history: 'Cronologia',
      preferences: 'Impostazioni',
      language: 'Lingua',
      by: 'di',
      addLanguage: 'Aggiungi lingua...',
      contributeOnGitHub: 'contribuisci su GitHub',
      account: 'Account',
      followers: 'Seguaci',
      followings: 'Seguiti',
      noHistory: 'Nessun dato nella cronologia',
      autoTweet: 'Tweet risultati',
      autoTweetDescription: 'Seleziona questa opzione per twittare automaticamente i tuoi risultati. Un tweet verrà pubblicato una volta che i risultati saranno pronti, non di più.',
      saveResults: 'Salva risultati',
      saveResultsDescription: 'Seleziona questa opzione per salvare i risultati nella cronologia (feature name + image + time). Per impostazione predefinita, non memorizziamo i tuoi risultati.',
      emojis: 'Pacchetto emoji',
      iOSemojis: 'iOS (Apple)',
      iOSemojisDescription: 'I tuoi risultati saranno generati con iOS Emojis.',
      androidEmojis: 'Android (Google)',
      androidEmojisDescription: 'I tuoi risultati verranno generati con Android Emojis.',
      clearHistory: 'Cancella la cronologia',
      clearHistoryDescription: 'Cancella la cronologia dei risultati Affinitweet.',
      deleteAccount: 'Elimina account',
      deleteAccountDescription: 'Elimina il tuo account Affinitweet, tutto andrà perduto.',
      show: 'Visualizza',
      showMore: 'Mostra di più...',
      saved: 'Salvato',
    },

    /* Feature page */
    feature: {
      login: 'Accedi per continuare...',
      startFeature: "Andiamo!",
      betaFeature: 'Questa funzione è attualmente in versione beta ed è disponibile solo per gli utenti che fanno parte del programma Beta. Puoi richiedere questo programma se vuoi testare questa funzione.',
      applyForFree: 'Candidati gratuitamente',
      results: "Ecco i tuoi risultati!",
      tweetResults: 'Tweet risultati',
      tweetingResults: 'Tweeting...',
      requireAutoTweetDescription: "Vuoi abilitare il tweet automatico dei risultati? Potrai disattivare questa opzione dal tuo profilo.",
      yesEnable: 'Si, Attiva',
      no: 'No',
      retry: 'Riprova!',
      doYouWantToKnowMore: 'Vuoi saperne di più sul tuo account Twitter?',
      discoverOtherFeatures: 'Scopri altre funzionalità',
    },

    /* Features listing page */
    features: {
      title: 'Caratteristiche',
      description: 'Scopri tutte le nostre funzionalità per sapere tutto sul tuo account Twitter.',
      searchFeatures: 'Funzionalità di ricerca... (ex: Top Friends, Valentine...)',
      noFeatureFound: 'Sfortunatamente nessuna funzione corrisponde a questa ricerca... 😔',
      resetSearch: 'Ripristina ricerca',
      letsGo: 'Andiamo!',
    },

    /* Beta program page */
    'beta-program': {
      title: 'Programma beta',
      description: 'Iscriviti gratuitamente al programma Beta e prova le nostre funzionalità beta prima che vengano rilasciate al pubblico!',
      betaProgramDescription: "Il programma Beta è stato creato per testare le nuove funzionalità prima che vengano rilasciate al pubblico per essere sicuri che funzionino come previsto. Facendo parte di questo programma, sarai in grado di testarli.",
      currentBetaFeatures: 'Attualmente {amount} {features} nel programma Beta:',
      noCurrentBetaFeatures: 'Al momento non ci sono funzionalità nel programma Beta, ma presto ne arriveranno altre!',
      fewThingsToKnow: 'Alcune cose da sapere sul programma Beta:',
      li1: "È gratuito al 100%",
      li2: "C'è un numero limitato di posti",
      li3: 'Puoi lasciarlo quando vuoi',
      li4: 'Supporto dedicato e prioritario su Twitter da DM',
      li5: 'Le funzionalità beta potrebbero non funzionare come previsto',
      li6: 'Le funzionalità beta possono cambiare in qualsiasi momento',
      thanksForInterest: 'Grazie per il tuo interesse riguardo al programma Beta 💜',
      alreadyApplied: "Sei già nel programma Beta,<br /> grazie mille per il tuo interesse 💜",
      leaveBetaProgram: 'Esci dal programma Beta',
      leavingTerms: "Se esci dal programma Beta, potresti non essere in grado di fare nuovamente domanda se non ci sono posti disponibili.",
      placesAvailable: '500 places available! 🎟',
      accountEligible: 'Il tuo account è idoneo per richiedere il programma Beta e sono disponibili pochi posti!',
      yourEmailAddress: 'Il tuo indirizzo di posta elettronica...',
      applyForFree: 'Candidati gratuitamente',
      applyTerms: 'Iscrivendoti al programma Beta, accetti di ricevere e-mail di notifica e promozione (massimo 1 una settimana).',
      noPlaceAvailable: 'Nessun posto disponibile 😕',
      betaProgramFull: "Sfortunatamente, il programma Beta è al completo e non possiamo fornire l'accesso gratuito in questo momento, ma puoi comunque provare a guadagnare un accesso utilizzando i metodi nel blocco successivo!",
      keepUpdated: 'Vi faremo sapere quando sarà disponibile il nuovo accesso gratuito su {ourTwitterAccount}.',
      ourTwitterAccount: 'il nostro account Twitter',
      or: 'o',
      earnYourAccess: 'Guadagna il tuo accesso! 🎁',
      writeReview: '#1 — Scrivi una recensione su di noi {onTrustpilot} e inviaci il suo link sul nostro account Twitter tramite DM, ti daremo quindi un accesso.',
      onTrustpilot: 'su Trustpilot',
      winContest: 'or #2 — Partecipa ai nostri concorsi su {ourTwitterAccount} per vincere un accesso, seguici e attiva le notifiche per essere sempre aggiornato.',
      randomDraws: 'Ciascuno di questi concorsi termina con una estrazione casuale effettuata su {pickaw}, così tutti hanno la possibilità di vincere.',
      welcomeToTheBetaProgram: 'Benvenuto nel programma Beta! Ora puoi testare le nostre funzionalità Beta 😊',
      seeYouSoonBetaProgram: 'Grazie per aver fatto parte del programma Beta, non vedo il momento di vederti',
    },

    /* Legal page */
    legal: {
      title: 'legale',
      description: 'Informazioni riguardo i nostri cookies.',
      intro: 'Ai sensi dell articolo 6 della legge n° 2004-575 del 21 giugno 2004 sulla fiducia della economia digitale, gli utenti del sito {site} sono informati della identità dei vari soggetti coinvolti nella sua attuazione e monitoraggio:',
      owner: 'Proprietario',
      creator: 'Creator',
      publisher: 'Responsabile della pubblicazione',
      publisherText: 'Il responsabile della pubblicazione è una persona fisica.',
      webmaster: 'Webmaster',
      host: 'Host',
      requestAddress: 'Indirizzo completo disponibile su richiesta via e-mail a {email}.',
      warningCookies: 'riaguardo i cookies',
      p1: 'Un cookie è un piccolo file di testo inviato al tuo browser tramite il sito web che stai visualizzando. Con questo cookie, le informazioni sulla tua visita vengono memorizzate sul sito web, come la tua lingua preferita e altre impostazioni. Ciò potrebbe facilitare la tua prossima visita a questo sito e renderlo più utile per te. I cookie svolgono un ruolo importante. Senza i cookie, non sarà possiboile utilizzare il Sito Web e potrebbe essere molto più frustrante.',
      t1: 'Qual è il quadro giuridico applicabile?',
      p2: "Nel modificare l'articolo 5, paragrafo 3, della direttiva 2002/58/CE adottando la direttiva 2009/136/CE, il legislatore europeo ha stabilito il principio secondo cui l'archiviazione delle informazioni sull'apparecchiatura di un utente o l'accesso alle informazioni già archiviate deve essere effettuata solo previo consenso dell'utente, salvo che tali azioni siano strettamente necessarie al fornitore per erogare un servizio espressamente richiesto dall'utente. L'articolo 32-II della legge del 6 gennaio 1978 riprende questo principio.",
      t2: 'Questo sito utilizza i cookie per i seguenti scopi:',
      'l1-1': 'Per aiutarci a riconoscere il tuo browser e per salvare le preferenze che hai impostato nelle tue precedenti visite a questo sito',
      'l1-2': 'Per aiutarci a misurare e studiare la efficacia dei nostri contenuti interattivi online, funzionalità, pubblicità e altre comunicazioni',
      'l1-3': 'Per monitorare i dati analitici sul sito, vengono utilizzati dal sito e da parte degli utenti per migliorare i servizi e i contenuti di questo sito.',
      t3: 'Come cancello i cookie collegati al mio browser?',
      p3: "Puoi scegliere di disabilitare i cookie nel tuo browser in qualsiasi momento seguendo le istruzioni fornite nei file di aiuto del tuo browser. Puoi anche impostare i cookie direttamente nelle impostazioni del browser:",
    },

    /* Terms of service page */
    terms: {
      title: 'Termini di servizio',
      description: 'Consulta le nostre condizioni generali di utilizzo.',
      h1: 'Termini',
      p1: 'Accedendo al sito web con questo indirizzo {url}, accetti di essere vincolato da questi termini di servizio, tutte le leggi e i regolamenti applicabili e accetti di essere responsabile del rispetto di qualsiasi legge locale applicabile. Se non sei d accordo con nessuno di questi termini, ti è vietato di usare o di accedere a questo sito. I materiali contenuti in questo sito Web sono protetti dalle leggi sul copyright e sui marchi applicabili.',
      h2: 'Licenza d uso',
      'l1-1': "È concesso il permesso di scaricare temporaneamente una copia dei materiali (informazioni o software) sul sito Web di Affinitweet solo per la visualizzazione transitoria personale e non commerciale. Questa è la concessione di una licenza, non un trasferimento di titolo, e in base a questa licenza non puoi:",
      'l2-1': 'modificare o copiare i materiali;',
      'l2-2': 'utilizzare i materiali per qualsiasi scopo commerciale o per qualsiasi esposizione pubblica (commerciale o non commerciale);',
      'l2-3': "tentare di decompilare o decodificare qualsiasi software contenuto nel sito Web di Affinitweet;",
      'l2-4': 'rimuovere qualsiasi copyright o altre notazioni di proprietà dai materiali; o',
      'l2-5': 'trasferire i materiali a un altra persona o "rispecchiare" i materiali su qualsiasi altro server.',
      'l1-2': 'Questa licenza terminerà automaticamente in caso di violazione di una qualsiasi di queste restrizioni e potrà essere rescissa da Affinitweet in qualsiasi momento. Al termine della visualizzazione di questi materiali o alla cessazione di questa licenza, è necessario distruggere qualsiasi materiale scaricato in proprio possesso, sia in formato elettronico che cartaceo.',
      h3: 'Dichiarazione di non responsabilità',
      'l3-1': "I materiali sul sito Web di Affinitweet sono forniti così come sono. Affinitweet non fornisce alcuna garanzia, espressa o implicita, e con la presente declina e nega tutte le altre garanzie incluse, senza limitazione, garanzie o condizioni implicite di commerciabilità, idoneità per uno scopo particolare o non violazione della proprietà intellettuale o altra violazione dei diritti.",
      'l3-2': 'Inoltre, Affinitweet non garantisce né rilascia alcuna dichiarazione in merito all accuratezza, ai risultati probabili o all affidabilità dell uso dei materiali sul proprio sito Web o altrimenti relativi a tali materiali o su qualsiasi sito collegato a questo sito.',
      h4: 'Limitazioni',
      p2: "In nessun caso Affinitweet o i suoi fornitori saranno responsabili per eventuali danni (inclusi, a titolo esemplificativo, danni per perdita di dati o profitto, o dovuti a interruzione dell'attività) derivanti dall'uso o dall'impossibilità di utilizzare i materiali sul sito Web di Affinitweet, anche se Affinitweet o un rappresentante autorizzato di Affinitweet è stato informato oralmente o per iscritto della possibilità di tale danno. Poiché alcune giurisdizioni non consentono limitazioni alle garanzie implicite o limitazioni di responsabilità per danni consequenziali o incidentali, queste limitazioni potrebbero non essere applicabili all'utente.",
      h5: 'Precisione dei materiali',
      p3: "I materiali che appaiono sul sito Web di Affinitweet potrebbero includere errori tecnici, tipografici o fotografici. Affinitweet non garantisce che nessuno dei materiali sul suo sito Web sia accurato, completo o aggiornato. Affinitweet può apportare modifiche ai materiali contenuti nel proprio sito Web in qualsiasi momento senza preavviso. Tuttavia Affinitweet non si impegna ad aggiornare i materiali.",
      h6: 'Links',
      p4: "Affinitweet non ha esaminato tutti i siti collegati al proprio sito Web e non è responsabile per i contenuti di tali siti collegati. L'inclusione di qualsiasi link non implica l'approvazione da parte di Affinitweet del sito. L'uso di tali siti Web collegati è a rischio dell'utente.",
      h7: 'Modifiche',
      p5: 'Affinitweet può rivedere questi termini di servizio per il proprio sito Web in qualsiasi momento senza preavviso. Utilizzando questo sito Web accetti di essere vincolato dalla versione corrente di questi termini di servizio.',
      h8: 'Legge governativa',
      p6: 'Questi termini e condizioni sono regolati e interpretati in conformità con le leggi della Francia e l utente si sottomette irrevocabilmente alla giurisdizione esclusiva dei tribunali di quello Stato o luogo.',
    },

    /* Data and privacy page */
    privacy: {
      title: 'Dati e privacy',
      description: 'Informazioni su come recuperiamo, analizziamo e conserviamo i tuoi dati.',
      intro: 'Prendiamo molto sul serio la privacy dei dati e nel corso della nostra attività desideriamo informare i nostri utenti su cosa ne facciamo. Di seguito troverai tutte le informazioni necessarie relative alla conservazione e al trattamento di questi dati. Le informazioni sui cookie sono disponibili anche su {thatPage}.',
      storage: 'Conservazione',
      personalData: 'Dati personali',
      p1: 'Quando accedi ad Affinitweet, raccogliamo dal tuo profilo Twitter le informazioni di cui abbiamo bisogno per offrirti i nostri servizi. Tra queste informazioni, memorizziamo il tuo:',
      'l1-1': 'unique Twitter ID',
      'l1-2': 'username (@)',
      'l1-3': 'nome',
      'l1-4': 'authentication token',
      'l1-5': 'authentication token secret',
      'l1-6': 'lingua',
      p2: 'Le altre informazioni che puoi vedere sul tuo profilo sono temporaneamente memorizzate nella tua sessione, basta disconnettersi per eliminarle.',
      i1: 'Informazioni: questi dati possono essere cancellati nella loro interezza e immediatamente semplicemente cliccando sul {button} in fondo a {yourProfile}.',
      results: 'Risultati',
      p3: 'Per impostazione predefinita, Affinitweet non memorizza i risultati di ciò che fai. Tuttavia, puoi attivare questa opzione per avere una cronologia dei tuoi risultati nel tuo profilo. Tra queste informazioni, memorizziamo:',
      'l2-1': 'l utente a cui appartiene il risultato',
      'l2-2': 'il nome della funzione',
      'l2-3': 'il timestamp del risultato',
      i2: 'Informativa: questi dati possono essere cancellati nella loro interezza ed immediatamente semplicemente cliccando sul {button} in fondo a {yourProfile}.',
      computing: 'in lavorazione',
      p4: 'Quando esegui le varie funzionalità presenti sul sito, effettuiamo chiamate all API di Twitter con i tuoi token precedentemente memorizzati.',
      i3: 'Informazioni: utilizziamo i tuoi token per essere il più precisi possibile nei nostri risultati. Quindi, se segui uno o più utenti con un account protetto, ad esempio, saremo in grado di includerli nei risultati se necessario.',
      p5: "Ecco cosa possiamo essere portati a ottenere:",
      'l3-1': 'your feed',
      'l3-2': 'your tweets/retweets',
      'l3-3': 'your mentions',
      'l3-4': 'your followers',
      'l3-5': 'your followings',
      p6: 'Queste informazioni vengono solo raccolte ed elaborate, non le memorizziamo.',
      publish: 'Pubblicazione',
      p7: 'Quando accedi ad Affinitweet, ti chiediamo l accesso in lettura di base al tuo account e l accesso in scrittura. Non effettueremo alcuna azione senza la tua espressa richiesta attivando un opzione dal sito.',
      i4: 'Informazioni: puoi revocare l accesso che ci hai fornito quando hai effettuato l accesso in qualsiasi momento dal tuo {yourTwitterProfile}.',
      autoTweet: 'Tweet automatico',
      p8: 'Per poter utilizzare determinate funzionalità, potremmo chiederti di abilitare l opzione tweet automatico per i risultati. Se accetti di abilitare questa opzione, verrà pubblicato un tweet per ogni risultato con l immagine generata.',
      i5: 'Informazioni: puoi disattivare questa opzione in qualsiasi momento da {yourProfile} nel {button} sezione.',
      question: 'Qualsiasi domanda?',
      p9: 'Se hai domande su Affinitweet, non esitare a contattarci via Twitter o e-mail, saremo felici di risponderti!',
      thatPage: 'questa pagina',
      yourProfile: 'Il tuo profilo',
      yourTwitterProfile: 'il tuo profilo Twitter',
    },

  },

  /* Errors */
  _er: {
    cooldown: 'This feature have a %{cooldown} seconds cooldown. Please retry in:',
    unknown: 'An error has occured. Our team has been notified.',
    unknownFeature: 'Unknown feature.',
    unavailableFeature: 'Unavailable feature.',
    betaFeature: "You can't use beta features until you're appart of the Beta program.",
    invalidEmail: 'Email is invalid.',
    selfUsername: 'Type a different username than yourself.',
    badUsername: 'Bad username.',
    notEnoughData: 'Not enough tweets to analyze.',
    errorWhileRendering: 'Error while generating image.',
    accountProtected: "You can't use this feature while your account is protected.",
    targetAccountProtectedAndNotFollowing: "You can't use this feature because the targeted user is protected and not following you.",
    timeout: 'Timeout exceeded.',
    twitterError: 'Twitter returned an error:',
    twitterErrors: {
      32: 'Could not authenticate you.',
      34: 'Sorry, that page does not exist.',
      50: 'User not found.',
      63: 'User has been suspended.',
      64: 'Your account is suspended and is not permitted to access this feature.',
      87: 'Client is not permitted to perform this action.',
      88: 'Rate limit exceeded. Retry in 15 minutes',
      89: 'Invalid or expired token. Please reconnect.',
      99: 'Unable to verify your credentials.',
      130: 'Over capacity.',
      131: 'Internal error.',
      135: 'Could not authenticate you.',
      144: 'No status found with that ID.',
      179: 'Sorry, you are not authorized to see this status.',
      185: 'User is over daily status update limit.',
      186: 'Tweet needs to be a bit shorter.',
      187: 'Status is a duplicate.',
      220: 'Your credentials do not allow access to this resource.',
      261: 'Application cannot perform write actions.',
      326: 'To protect our users from spam and other malicious activity, this account is temporarily locked.',
    },
  },

}
