export default {

  /* Layouts */
  _lt: {

    default: {
      cookiesBanner: 'Ми використовуємо кукі🍪, щоб вам було легше сайтом. Продовжуючи користуватися нашим вебсайтом, ви погоджуєтеся з нашою політикою кукі. {button}',
      readMore: 'Читати більше...',
    },

  },

  /* Common */
  _cm: {
    lastRevision: 'Останнє оновлення:',
    contactUs: 'Звʼяжіться з нами',
    followUs: 'Слідкуйте за нами',
    reviewUs: 'Оцініть нас',
    close: 'Закрити',
    cancel: 'Скасувати',
  },

  /* Languages */
  _lg: {
    french: 'Французька',
    english: 'Англійська',
    polish: 'Польска',
    spanish: 'Іспанська',
    swedish: 'Шведська',
    turkish: 'Турецька',
    indonesian: 'Індонезійська',
    portuguese: 'Португальска',
    simplifiedChinese: 'Китайська спрощена',
    traditionalChinese: 'Китайська традиційна',
  },

  /* Pluralization */
  _pl: {
    seconds: 'second | second | seconds',
    features: 'feature | feature | features',
  },

  /* Components */
  _cp: {

    /* Header component */
    header: {
      sidebarHint: 'Спробуйте усі наші функції, натиснувши на значок меню тут! 😉',
      logIn: 'Увійти',
      myAccount: 'Мій акаунт',
      switchAccount: 'Змінити акаунт',
      logout: 'Вийти',
    },

    /* Footer component */
    footer: {
      madeWithLove: 'Affinitweet це розважально-статистична платформа, що базується на Twitter і яка була  створена у 2015 з ❤️ з Франції.',
      allRightsReserved: 'Усі прав збережено.',
      about: 'Про нас',
      changelog: 'Зміноопис',
      legal: 'Права',
      partners: 'Партнери',
    },

    stateButton: {
      hold: 'Утримуйте, щоб продовжити',
      submit: 'Натисніть, щоб продовжити',
      loading: 'Дія в процесі...',
      cancel: 'Скасувати',
    },

    clearHistory: {
      title: 'Очистити історію',
      description: 'Очищуючи свою історію, ви видалите всю інформацію і зображення ваших поточних збережених результаті.',
      description2: 'Ви не будете здатні переглядати свох попередні результати після очищення, ви справді хочете це зробити?',
      holdButton: 'Утримуйте, щоб очистити',
      loadingButton: 'Очищення історії...',
      successModal: 'Вашу історію очищено.',
    },

    deleteAccount: {
      title: 'Видалити акаунт',
      description: 'Щось не пішло не так? Розкажіть нам про це в наш Twitter акаунт, щоб ми мали змогли поліпшити!',
      description2: 'Видаляючи акаунт, усі дані про вас видалитимуться, включаючи історію. Ніякі дані не залишуться і ви автоматично вийдете з Affinitweet.',
      description3: 'Ви не зможете відновити свій поточний акаунт після видалення, ви справді хочете це зробити?',
      holdButton: 'Утримуйте, щоб видалити',
      loadingButton: 'Видалення акаунту...',
      successModal: 'Ваш акаунт видалено.',
    },

  },

  /* Features */
  _ft: {

    new: 'Нове',
    popular: 'Популярне',
    real: 'Корисне',
    fun: 'Забавка',

    list: {

      friendships: {
        description: 'Everything you need to know about the links between you and a user! 🙌',
        longDescription: 'Thanks to Friendships you will know how much you are friends with another user of your choice: the more blue pellets you have, the stronger the links are! Enter the Twitter nickname of the chosen person and discover your Friendships!',
      },
      'common-friends': {
        description: 'Discover your friends in common with another user! 👥',
        longDescription: 'The Common Friends allows you to discover the subscriptions/friends you have in common with another person. Do you have the same tastes, and how much?',
      },
      'top-friends': {
        description: 'Discover your best Twitter friends of late! 🤗',
        longDescription: 'The Top Friends allows you to know who your best friends are on Twitter. We establish a ranking by analyzing the information sent and received by your account. Then we count, add and sort them to generate your Top Friends!',
      },
      'famous-followers': {
        description: 'Discover the most popular people in your followers! 💅',
        longDescription: 'The Famous Followers allows you to know which people have the most followers among your followers. We collect each of your followers and their number of followers and sort them to generate your Famous Followers!',
      },
      valentine: {
        description: 'We know who your Valentine will be this year... What about you? 💏',
        longDescription: 'We keep the algorithm of this feature secret. All we can say is that we are trying to stick to reality, will our Valentine delight you... ?',
      },
      'twitter-activity': {
        description: 'Discover the summary of your activity and your Twitter statistics 📊',
        longDescription: 'Thanks to Twitter Activity, you will know when you tweet most often, how many interactions (impressions, retweets, likes, replies) you have in total and the distribution of your tweets.',
      },
      'first-follower': {
        description: 'Discover who\'s the first person who followed you on Twitter 1️⃣',
        longDescription: 'Thanks to the First Follower, you\'ll know who is your first follower and when they followed you (or the oldest one, because if you\'ve been unfollowed in the meantime, we can\'t know).',
      },
      'first-following': {
        description: 'Discover who\'s the first person you followed on Twitter 1️⃣',
        longDescription: 'Thanks to the First Following, you\'ll know who is your first following and when you followed them (or the oldest one, because if you\'ve unfollowed people in the meantime, we can\'t know).',
      },
      'secret-crush': {
        description: 'Someone loves you in secret... and hides it from you... 😳',
        longDescription: 'We keep the algorithm of this feature secret. All we can say is that your Secret Crush will impress you, good or bad?',
      },
      'hidden-twin': {
        description: 'Yes, you have a hidden twin.... who the hell is it? 🤔',
        longDescription: 'We keep the algorithm of this feature secret. All we can say is that your Hidden Twin will impress you, good or bad?',
      },
      'stolen-kiss': {
        description: 'Who wants to steal a kiss from you on a street corner? 💋',
        longDescription: 'We keep the algorithm of this feature secret. All we can say is that your Stolen Kiss will impress you, good or bad?',
      },
      'may-day': {
        description: 'Who\'s your best bouquet for this year? 💐',
        longDescription: 'We keep the algorithm of this feature secret. All we can say is that you\'re going to make someone very happy!',
      },
      'halloween-duo': {
        description: 'Who will you be most afraid with this year? 🎃👻',
        longDescription: 'We keep the algorithm of this feature secret. All we can say is that you\'re going to be scary for Halloween this year!',
      },
      'tweet-rate': {
        description: 'Compare your tweet rate with another user! 📊',
        longDescription: 'The Tweet Rate allows you to know the average number of tweets you publish per day since you registered on Twitter and compare yourself with another person! Are you the most active?',
      },
      'first-to-follow': {
        description: 'Find out when you\'ve been following a user and vice versa! 😮',
        longDescription: 'The First To Follow allows you to discover the date and time you followed another person on Twitter, and vice versa! Who followed the other first?',
      },
      'emoji-mood': {
        description: 'What are the emojis you tweet the most? 🤖',
        longDescription: 'Thanks to the Emoji Mood, you will discover which emotions you have been tweeting the most recently... Would you be willing to bet on your TOP 3?',
      },
      'new-years-kiss': {
        description: 'Who are you going to kiss this year under the mistletoe? 😘',
        longDescription: 'We keep the algorithm of this feature secret. All we can say is that you will kiss someone at midnight!',
      },

    },

  },

  /* Pages */
  _pg: {

    /* Welcome page */
    welcome: {
      title: 'Ласкаво просимо',
      welcomeToAffinitweet: 'Ласкаво просимо до Affinitweet&nbsp;&nbsp;🎉',
      helloYou: 'Здрастуйте, {username}&nbsp;&nbsp;😊',
      proudToWelcomeYou: 'Вітаю, {username}, we are delighted to make your acquaintance and happy to welcome you among our more than 6 million users!',
      onboardingCreation: 'We are delighted to have you back with us! We created this little onboarding to make sure you know everything before everyone else...',
      next: 'Далы',
      littleQuestion: 'Quick question...',
      doYouWantToFollowUs: 'We update Affinitweet regularly, do you want to follow us on Twitter to find out when new features will be available?',
      iWantToFollowYou: 'I want to follow you 😊',
      iDontWantToFollowYou: 'No thanks, I\'m good for now!',
      great: 'Great&nbsp;&nbsp;🥰',
      doYouWantToEnableNotifications: 'So, while you\'re at it, do you want to be notified of our tweets so you can be the first to test our new features?',
      iWantToBeNotified: 'I also want to be notified 😇',
      iDontWantToBeNotified: 'No, I just want the tweets!',
      noProblem: 'No problem&nbsp;&nbsp;😉',
      noProblemDescription: 'After all you\'re right, we hardly know each other! Maybe next time then, we hope you\'ll have fun on Affinitweet 💜',
      nice: 'Nice&nbsp;&nbsp;🤗',
      niceDescription: 'Hop... hop... and hop!<br />That\'s it, you\'re now following us on Twitter! Thanks a lot and have fun on Affinitweet 💜',
      awesome: 'Awesome&nbsp;&nbsp;😍',
      awesomeDescription: 'Hop... hop... and hop!<br /><br />That\'s it, you\'re now following us on Twitter and notifications have been enabled! Thanks a lot and have fun on Affinitweet 💜',
      letsGo: 'Let\'s go!',
    },

    /* Home page */
    index: {
      title: 'Домівка',
      description: 'Найкраще місце для розваги разом з друзями у Twitter! Перевірте свою статистику і не тільки!',
      titleH1: 'Найкраще місце для розваги разом з друзями у Twitter!',
      titleH2: 'Перевірте свою статистику і не тільки!',
      highlights: 'Основні особливості',
      generatedResults: 'Прекрасно згенеровані результати',
      generatedResultsDescription: 'Affinitweet відомий за свої прекрасно створені зображення, ми використовуємо лише найкращі інструменти, щоб досягти результату.',
      userConsentPrivacy: 'Користувацька згода і приватність',
      userConsentPrivacyDescription: 'Усе, що ми робимо на Affinitweet з вашими даними, пояснено у нашій політиці конфеденційності, без підводних каменів, без автопідписування чи автотвітівn.',
      worldFamousLeader: 'Усесвітньо світовий лідер',
      worldFamousLeaderDescription: 'Affinitweet відкрито у лютому 2014, і понад двох мільйонів користувачів використовують наші сервіси у всьому світі.',
      fastRealTimeResults: 'Швидкі результати у реальному часі',
      fastRealTimeResultsDescription: "Ми побудували Affinitweet за допомогою останніх вебтехнологій, тому це максимально швидко завдяки реальному часу на сторінках особливостей сайту.",
      noAdsNoVirus: 'Немає настирливої реклами чи вірусів',
      noAdsNoVirusDescription: "Affinitweet було створено виключно для розваги, тут немає вірусів, а є лише 2 рекламні оголошенняна цілому сайті (без спливних сповіщень чи переспрямувань).",
      multilingualOpen: 'Багатомовні і відкриті',
      multilingualOpenDescription: 'Affinitweet доступний декількома мовами, і кожен може зробити внесок, щоб додати свою власну мову.',
      trustpilotH1: "Перевірте відгуки наших користувачів на Trustpilot!",
      trustpilotH2: 'Нас оцінило вже близько {rate} користувачів, чи не станете ви наступним?',
      trustpilotButton: 'Подивитися і написати відгук',
      statistics: 'Статистика',
      totalUsers: '6 мільйонів',
      totalUsersDescription: 'Користувачів довіряють нам і нашим сервісам',
      monthlyUsers: '400 000',
      monthlyUsersDescription: 'Унікальних користувачів, які повертаються в середньому за місяць',
      totalFeatures: '20 мільйонів',
      totalFeaturesDoneDescription: 'Особливостей зроблено з нашого відкриття в 2014',
      features: 'Особливості',
      latestNews: 'Останні новини',
      getInTouch: 'Залишайтесь на звʼязку!',
      getInTouchP1: 'Ми доступні в будь-який час у нашому акаунті у Twitter {twitterName}.',
      getInTouchP2: 'Стежте за нами і ви знатимете все про майбутні оновлення!',
      getInTouchP3: 'Не соромтеся надсилати нам твіт чи приватне повідомлення, якщо у вас є питання, пропозиція чи знайдена хиба.',
      getInTouchP4: 'Якщо у вас є комерційна пропозиція, то ви можете написати нам на електронну пошту, дивіться наступну сторінку — {pageName}.',
    },

    /* User profile page */
    profile: {
      title: 'Профіль',
      description: 'Акаунт, налаштування й історія вашого профілю.',
      joinBeta: 'Долучіться до програми бета-тестування, що протестувати нові особливості до оприлюднення!',
      betaTerms: 'Бета-тестування безкоштовне. Деякі особливості можуть не працювати і можуть бути модифікованими до оприлюднення.',
      applyForFree: 'Подати заявку безкоштовно',
      noThanks: 'Ні, дякую',
      profile: 'Профіль',
      history: 'Історія',
      preferences: 'Уподобання',
      language: 'Мова',
      by: 'від',
      addLanguage: 'додати мову...',
      contributeOnGitHub: 'зробити внесок на GitHub',
      account: 'Акаунт',
      followers: 'Підписники',
      followings: 'Ви читаєте',
      noHistory: 'Немаж даних історії.',
      autoTweet: 'Результати твіту',
      autoTweetDescription: 'Увімкніть цю опцію, щоб автоматично зробити твіт про свої результати. Ми опублікуємо твіт, коли результати будуть готові. Лише один твіт.',
      saveResults: 'Зберегти результати',
      saveResultsDescription: 'Увімкніть цю опцію, щоб зберегти свою результати до історії (назва особливості + зображення + час). За замовчуванням, ми не зберігаємо ваші результати.',
      emojis: 'Пакунок смайликів',
      iOSemojis: 'iOS (Apple)',
      iOSemojisDescription: 'Ваші результати створюватимуться зі смайликами iOS.',
      androidEmojis: 'Android (Google)',
      androidEmojisDescription: 'Ваші результати створюватимуться зі смайликами Android.',
      clearHistory: 'Очистити історію',
      clearHistoryDescription: 'Очистити історію результатів Affinitweet.',
      deleteAccount: 'Видалити акаунт',
      deleteAccountDescription: 'Видалити свій Affinitweet account, ви все загубите.',
      show: 'переглянути',
      showMore: 'Показати більше...',
      saved: 'Збережено',
    },

    /* Feature page */
    feature: {
      login: 'Log in to continue...',
      startFeature: "Let's go!",
      betaFeature: 'This feature is currently in beta and is available for users being part of the Beta program only. You can apply for this program if you want to test this feature.',
      applyForFree: 'Apply for free',
      results: "Here's your results!",
      tweetResults: 'Tweet results',
      tweetingResults: 'Tweeting...',
      requireAutoTweetDescription: "Do you want to enable auto-tweet results? You'll be able to deactivate this option from your profile.",
      yesEnable: 'Yes, enable',
      no: 'No',
      retry: 'Retry!',
      doYouWantToKnowMore: 'Do you want to learn more about your Twitter account?',
      discoverOtherFeatures: 'Discover more features',
    },

    /* Features listing page */
    features: {
      title: 'Features',
      description: 'Discover all our features to know everything about your Twitter account.',
      searchFeatures: 'Search features... (ex: Top Friends, Valentine...)',
      noFeatureFound: 'Unfortunately no feature matches this search... 😔',
      resetSearch: 'Reset search',
      letsGo: 'Let\'s go!',
    },

    /* Beta program page */
    'beta-program': {
      title: 'Beta program',
      description: 'Apply to the Beta program for free and try our beta features before they get released to the public!',
      betaProgramDescription: "The Beta program has been created to test new features before they get released to the public to be sure that they're working as expected. By being part of this program, you will be able to test them.",
      currentBetaFeatures: 'There\'s currently {amount} {features} in the Beta program:',
      noCurrentBetaFeatures: 'There\'s currently no feature in the Beta program, but more are coming soon!',
      fewThingsToKnow: 'Few things to know about the Beta program:',
      li1: "It's 100% free of charge",
      li2: "There's a limited number of places",
      li3: 'You can leave it when you want',
      li4: 'Dedicated & priority support on Twitter by DM',
      li5: 'Beta features might not work as expected',
      li6: 'Beta features can change at anytime',
      thanksForInterest: 'Thank you for your interest regarding the Beta program 💜',
      alreadyApplied: "You're already in the Beta program,<br />thank you so much for your interest 💜",
      leaveBetaProgram: 'Leave the Beta program',
      leavingTerms: "If you leave the Beta Program, you may not be able to apply again if there's no available places.",
      placesAvailable: '500 places available! 🎟',
      accountEligible: 'Your account is eligible to apply for the Beta program and few places are available!',
      yourEmailAddress: 'Your email address...',
      applyForFree: 'Apply for free',
      applyTerms: 'By applying to the Beta program, you agree to receive notification & promotion emails (1 per week maximum).',
      noPlaceAvailable: 'No place available 😕',
      betaProgramFull: "Unfortunately, the Beta program is full and we can't give free access at this time, but you can still try to earn an access by using the methods in the next block!",
      keepUpdated: 'We will let you know when new free access will be available on {ourTwitterAccount}.',
      ourTwitterAccount: 'our Twitter Account',
      or: 'or',
      earnYourAccess: 'Earn your access! 🎁',
      writeReview: '#1 — Write a review about us {onTrustpilot} and send us its link on our Twitter account by DM, we will then give you an access.',
      onTrustpilot: 'on Trustpilot',
      winContest: 'or #2 — Participate in our contests on {ourTwitterAccount} to win an access, follow us and enable notifications to keep updated.',
      randomDraws: 'Each of these contests ends with a random draw made on {pickaw}, so everyone have a chance to win.',
      welcomeToTheBetaProgram: 'Welcome to the Beta program! You can now test our Beta features 😊',
      seeYouSoonBetaProgram: 'Thanks for being part of the Beta program, can\'t wait to see you soon!',
    },

    /* Legal page */
    legal: {
      title: 'Legal',
      description: 'Information about us and cookies.',
      intro: 'In accordance with Article 6 of the law n° 2004-575 of 21 June 2004 on trust in the digital economy, users of the site {site} are informed of the identity of the various parties involved in its implementation and monitoring:',
      owner: 'Owner',
      creator: 'Creator',
      publisher: 'Publication manager',
      publisherText: 'The person responsible for publication is a natural person.',
      webmaster: 'Webmaster',
      host: 'Host',
      requestAddress: 'Full address available on request by email at {email}.',
      warningCookies: 'About cookies',
      p1: 'A cookie is a small text file sent to your browser via the website you are viewing. With this cookie, information about your visit is stored on the website, such as your preferred language and other settings. This may facilitate your next visit to this site and make it more useful to you. Cookies play an important role. Without cookies, using the Web could be much more frustrating.',
      t1: 'What is the applicable legal frame?',
      p2: "In amending Article 5(3) of Directive 2002/58/EC by adopting Directive 2009/136/EC, the European legislator laid down the principle that the storage of information on a user's equipment or access to information already stored should only be carried out with the user's prior consent, unless these actions are strictly necessary for the provider to deliver a service expressly requested by the user. Article 32-II of the law of 6 January 1978 takes over this principle.",
      t2: 'This site uses cookies for the following purposes:',
      'l1-1': 'To help us recognize your browser and to save the preferences you have set in your previous visits to this site',
      'l1-2': 'To help us measure and study the effectiveness of our online interactive content, features, advertising and other communications',
      'l1-3': 'To monitor the analytical data on the site, the use made of the site by users and to improve the services and content of this site.',
      t3: 'How do I delete cookies linked to my browser?',
      p3: "You can choose to disable cookies in your browser at any time by following the instructions provided in your browser's help files. You can also set your cookies directly in your browser settings:",
    },

    /* Terms of service page */
    terms: {
      title: 'Terms of service',
      description: 'Consult our general terms and conditions of use.',
      h1: 'Terms',
      p1: 'By accessing the website at {url}, you are agreeing to be bound by these terms of service, all applicable laws and regulations, and agree that you are responsible for compliance with any applicable local laws. If you do not agree with any of these terms, you are prohibited from using or accessing this site. The materials contained in this website are protected by applicable copyright and trademark law.',
      h2: 'Use Licence',
      'l1-1': "Permission is granted to temporarily download one copy of the materials (information or software) on Affinitweet's website for personal, non-commercial transitory viewing only. This is the grant of a license, not a transfer of title, and under this license you may not:",
      'l2-1': 'modify or copy the materials;',
      'l2-2': 'use the materials for any commercial purpose, or for any public display (commercial or non-commercial);',
      'l2-3': "attempt to decompile or reverse engineer any software contained on Affinitweet's website;",
      'l2-4': 'remove any copyright or other proprietary notations from the materials; or',
      'l2-5': 'transfer the materials to another person or "mirror" the materials on any other server.',
      'l1-2': 'This license shall automatically terminate if you violate any of these restrictions and may be terminated by Affinitweet at any time. Upon terminating your viewing of these materials or upon the termination of this license, you must destroy any downloaded materials in your possession whether in electronic or printed format.',
      h3: 'Disclaimer',
      'l3-1': "The materials on Affinitweet's website are provided on an 'as is' basis. Affinitweet makes no warranties, expressed or implied, and hereby disclaims and negates all other warranties including, without limitation, implied warranties or conditions of merchantability, fitness for a particular purpose, or non-infringement of intellectual property or other violation of rights.",
      'l3-2': 'Further, Affinitweet does not warrant or make any representations concerning the accuracy, likely results, or reliability of the use of the materials on its website or otherwise relating to such materials or on any sites linked to this site.',
      h4: 'Limitations',
      p2: "In no event shall Affinitweet or its suppliers be liable for any damages (including, without limitation, damages for loss of data or profit, or due to business interruption) arising out of the use or inability to use the materials on Affinitweet's website, even if Affinitweet or a Affinitweet authorized representative has been notified orally or in writing of the possibility of such damage. Because some jurisdictions do not allow limitations on implied warranties, or limitations of liability for consequential or incidental damages, these limitations may not apply to you.",
      h5: 'Accuracy of materials',
      p3: "The materials appearing on Affinitweet's website could include technical, typographical, or photographic errors. Affinitweet does not warrant that any of the materials on its website are accurate, complete or current. Affinitweet may make changes to the materials contained on its website at any time without notice. However Affinitweet does not make any commitment to update the materials.",
      h6: 'Links',
      p4: "Affinitweet has not reviewed all of the sites linked to its website and is not responsible for the contents of any such linked site. The inclusion of any link does not imply endorsement by Affinitweet of the site. Use of any such linked website is at the user's own risk.",
      h7: 'Modifications',
      p5: 'Affinitweet may revise these terms of service for its website at any time without notice. By using this website you are agreeing to be bound by the then current version of these terms of service.',
      h8: 'Governing Law',
      p6: 'These terms and conditions are governed by and construed in accordance with the laws of France and you irrevocably submit to the exclusive jurisdiction of the courts in that State or location.',
    },

    /* Data and privacy page */
    privacy: {
      title: 'Data and privacy',
      description: 'Information on how we retrieve, analyze and store your data.',
      intro: 'We take the privacy of data very seriously and in the course of our business, we want to inform our users about what we do with it. You will find below all the necessary information concerning the storage and processing of this data. Information about cookies is also available on {thatPage}.',
      storage: 'Storage',
      personalData: 'Personal data',
      p1: 'When you log into Affinitweet, we collect the information from your Twitter profile that we need in order to offer you our services. Among this information, we store your:',
      'l1-1': 'unique Twitter ID',
      'l1-2': 'username (@)',
      'l1-3': 'name',
      'l1-4': 'authentication token',
      'l1-5': 'authentication token secret',
      'l1-6': 'language',
      p2: 'The other information you can see on your profile is temporarily stored in your session, just log out to delete it.',
      i1: 'Information: these data can be deleted in their entirety and immediately on simply clicking on {button} at the bottom of {yourProfile}.',
      results: 'Results',
      p3: 'By default, Affinitweet does not store the results of what you do. However, you can activate this option to have a history of your results in your profile. Among this information, we store:',
      'l2-1': 'the user to whom the result belongs',
      'l2-2': 'the name of the feature',
      'l2-3': 'the timestamp of the result',
      i2: 'Information: these data can be deleted in their entirety and immediately by simply clicking on {button} at the bottom of {yourProfile}.',
      computing: 'Processing',
      p4: 'When you perform the various features present on the site, we make calls to the Twitter API with your previously stored tokens.',
      i3: 'Information: we use your tokens to be able being as accurate as possible in our results. Thus, if you follow one or more users with a protected account for example, we will be able to include them in the results if necessary.',
      p5: "Here's what we can be led to get:",
      'l3-1': 'your feed',
      'l3-2': 'your tweets/retweets',
      'l3-3': 'your mentions',
      'l3-4': 'your followers',
      'l3-5': 'your followings',
      p6: 'This information is only collected and processed, we do not store it.',
      publish: 'Publication',
      p7: 'When you log in to Affinitweet, we ask for basic read access to your account and write access. We will not carry out any action without your express request by activating an option from the site.',
      i4: 'Information: you can revoke the access you gave us when you logged in at any time from your {yourTwitterProfile}.',
      autoTweet: 'Automatic tweet',
      p8: 'In order to be able to use certain features, we may ask you to enable the automatic tweet option for results. If you agree to enable this option, a tweet will be published for each result with the generated image.',
      i5: 'Information: you can deactivate this option at any time from {yourProfile} in the {button} section.',
      question: 'Any questions?',
      p9: 'If you have any questions about Affinitweet, please do not hesitate to contact us via Twitter or email, we will be happy to answer you!',
      thatPage: 'this page',
      yourProfile: 'your profile',
      yourTwitterProfile: 'your Twitter profile',
    },

  },

  /* Errors */
  _er: {
    cooldown: 'This feature have a %{cooldown} seconds cooldown. Please retry in:',
    unknown: 'An error has occured. Our team has been notified.',
    unknownFeature: 'Unknown feature.',
    unavailableFeature: 'Unavailable feature.',
    betaFeature: "You can't use beta features until you're appart of the Beta program.",
    invalidEmail: 'Email is invalid.',
    selfUsername: 'Type a different username than yourself.',
    badUsername: 'Bad username.',
    notEnoughData: 'Not enough tweets to analyze.',
    errorWhileRendering: 'Error while generating image.',
    accountProtected: "You can't use this feature while your account is protected.",
    targetAccountProtectedAndNotFollowing: "You can't use this feature because the targeted user is protected and not following you.",
    timeout: 'Timeout exceeded.',
    twitterError: 'Twitter returned an error:',
    twitterErrors: {
      32: 'Could not authenticate you.',
      34: 'Sorry, that page does not exist.',
      50: 'User not found.',
      63: 'User has been suspended.',
      64: 'Your account is suspended and is not permitted to access this feature.',
      87: 'Client is not permitted to perform this action.',
      88: 'Rate limit exceeded. Retry in 15 minutes',
      89: 'Invalid or expired token. Please reconnect.',
      99: 'Unable to verify your credentials.',
      130: 'Over capacity.',
      131: 'Internal error.',
      135: 'Could not authenticate you.',
      144: 'No status found with that ID.',
      179: 'Sorry, you are not authorized to see this status.',
      185: 'User is over daily status update limit.',
      186: 'Tweet needs to be a bit shorter.',
      187: 'Status is a duplicate.',
      220: 'Your credentials do not allow access to this resource.',
      261: 'Application cannot perform write actions.',
      326: 'To protect our users from spam and other malicious activity, this account is temporarily locked.',
    },
  },

}
