export default {

  /* Layouts */
  _lt: {

    default: {
      cookiesBanner: 'We gebruiken cookies 🍪 om je de beste ervaring te bieden. Als je doorgaat naar onze website, ga ja akkoord met ons cookiebeleid. {button}',
      readMore: 'Meer hierover...',
    },

  },

  /* Common */
  _cm: {
    lastRevision: 'Laatst bijgewerkt:',
    contactUs: 'Contact opnemen',
    followUs: 'Volgen',
    reviewUs: 'Beoordelen',
    close: 'Sluiten',
    cancel: 'Annuleren',
  },

  /* Languages */
  _lg: {
    french: 'Frans',
    english: 'Engels',
    polish: 'Pools',
    spanish: 'Spaans',
    swedish: 'Zweeds',
    turkish: 'Turks',
    indonesian: 'Indonesisch',
    portuguese: 'Portugees',
    simplifiedChinese: 'Vereenvoudigd Chinees',
    traditionalChinese: 'Traditioneel Chinees',
    dutch: "Nederlands",
  },

  /* Pluralization */
  _pl: {
    seconds: 'seconden | seconde | seconden',
    features: 'functies | functie | functies',
  },

  /* Components */
  _cp: {

    /* Header component */
    header: {
      sidebarHint: 'Ontdek alle functies onder dit menu-icoon! 😉',
      logIn: 'Inloggen',
      myAccount: 'Mijn account',
      switchAccount: 'Account wijzigen',
      logout: 'Uitloggen',
    },

    /* Footer component */
    footer: {
      madeWithLove: 'Affinitweet is een op Twitter gebaseerd statistiek- en vermaakplatform, in 2015 met ❤️ gemaakt in Frankrijk.',
      allRightsReserved: 'Alle rechten voorbehouden.',
      about: 'Over',
      changelog: 'Changelos',
      legal: 'Juridisch',
      partners: 'Partners',
    },

    stateButton: {
      hold: 'Houd ingedrukt om te bevestigen',
      submit: 'Klik om te bevestigen',
      loading: 'Actie wordt uitgevoerd...',
      cancel: 'Annuleren',
    },

    clearHistory: {
      title: 'Geschiedenis legen',
      description: 'Door je geschiedenis te legen worden alle informatie en afbeeldingen van je opgeslagen resultaten verwijderd.',
      description2: 'Je kunt je vorige resultaten hierna niet meer zien, wil je deze actie echt uitvoeren?',
      holdButton: 'Houd ingedrukt om te legen',
      loadingButton: 'Geschiedenis legen...',
      successModal: 'Je geschiedenis is geleegd.',
    },

    deleteAccount: {
      title: 'Account verwijderen',
      description: 'Is er iets misgegaan? Laat het ons weten op Twitter en help ons te verbeteren!',
      description2: 'Door je account te verwijderen wordt al je data verwijderd, waaronder je geschiedenis. Er wordt niks behouden en je wordt automatisch uitgelogd op Affinitweet.',
      description3: 'Je kunt je account hierna niet meer terugzetten, wil je deze actie echt uitvoeren?',
      holdButton: 'Houd ingedrukt om te verwijderen',
      loadingButton: 'Account verwijderen...',
      successModal: 'Je account is verwijderd.',
    },

  },

  /* Features */
  _ft: {

    new: 'Nieuw',
    popular: 'Populair',
    real: 'Echt',
    fun: 'Plezier',

    list: {

      friendships: {
        description: 'Alles wat je moet weten over de connectie tussen jou en een gebruiker! 🙌',
        longDescription: 'Met Friendships kun je zien hoe goed je bent bevriend met een andere gebruiker: hoe meer bolletjes, des te sterker de connectie! Voer de Twitter-naam van een gebruiker in en ontdek Friendships!',
      },
      'common-friends': {
        description: 'Ontdek je gemeeschappelijke vrienden met een andere gebruiker! 👥',
        longDescription: 'Common Friends staat je toe om abonnementen/vrienden die je deelt met anderen te zien. Hebben jullie dezelfde smaak?',
      },
      'top-friends': {
        description: 'Ontdek je beste Twitter-vrienden! 🤗',
        longDescription: 'In Top Friends wie je beste vrienden zijn op Twitter. We maken een lijst op basis van de informatie die verzonden en ontvangen wordt van je account. Daarna tellen we, berekenen we en sorteren we ze om je Top Friends te maken!',
      },
      'famous-followers': {
        description: 'Vind je populairste volger! 💅',
        longDescription: 'Met Famous Followers kun je zien welk van je volgers de meeste volgers heeft. We bekijken al je volgers en hoeveel volgers zij hebben en sorteren ze om je Famous Followers te vormen!',
      },
      valentine: {
        description: 'Wij weten al wie je valentijn is dit jaar... Jij ook? 💏',
        longDescription: 'Hoe dit werkt, is ons geheimpje. Wat we wel kunnen zeggen is dat we zo realistisch mogelijk blijven. Zal je blij zijn met je valentijn... ?',
      },
      'twitter-activity': {
        description: 'Bekijk een overzicht van je Twitter-activiteit en -statistieken 📊',
        longDescription: 'Dankzij Twitter Activity weet je wanneer je het vaakst tweet, hoeveel interacties (impressies, retweets, vind-ik-leuks, reacties) je hebt in totaal en de verspreiding van je tweets.',
      },
      'first-follower': {
        description: 'Vind uit wie je eerste volger op Twitter is 1️⃣',
        longDescription: 'Dankzij First Follower weet je wie je eerste volger is en wanneer deze je heeft gevolgd (of je oudste volger, want als je je eerste hebt ontvolgd kunnen we deze niet achterhalen).',
      },
      'first-following': {
        description: 'Discover who\'s the first person you followed on Twitter 1️⃣',
        longDescription: 'Dankzij First Following weet je wie je als eerst hebt gevolgd en wanneer je dit hebt gedaan (of je oudste volgend, want als je je eerste hebt ontvolgd kunnen we deze niet achterhalen).',
      },
      'secret-crush': {
        description: 'Stiekem houdt iemand van je... maar zegt het niet... 😳',
        longDescription: 'Hoe dit werkt, is ons geheimpje. Wat we wel kunnen zeggen is dat je Secret Crush je (on)aangenaam zal verassen...',
      },
      'hidden-twin': {
        description: 'Ja, je hebt een geheime tweeling... wie o wie? 🤔',
        longDescription: 'Hoe dit werkt, is ons geheimpje. Wat we wel kunnen zeggen is dat je Hidden Twin je (on)aangenaam zal verassen...',
      },
      'stolen-kiss': {
        description: 'Wie wilt je kus afpakken in het steegje achter? 💋',
        longDescription: 'Hoe dit werkt, is ons geheimpje. Wat we wel kunnen zeggen is dat je Stolen Kiss je (on)aangenaam zal verassen...',
      },
      'may-day': {
        description: 'Voor wie is je bos bloemen dit jaar? 💐',
        longDescription: 'Hoe dit werkt, is ons geheimpje. Wat we wel kunnen zeggen is dat je iemand dolblij zult maken!',
      },
      'halloween-duo': {
        description: 'Met wie ben jij dit jaar het bangst? 🎃👻',
        longDescription: 'Hoe dit werkt, is ons geheimpje. Wat we wel kunnen zeggen is dat je dit jaar met Halloween heel eng zult zijn!',
      },
      'tweet-rate': {
        description: 'Vergelijk je tweetsnelheid met iemand anders! 📊',
        longDescription: 'In Tweet Rate zie je het gemiddeld aantal tweets dat je plaatst per dag sinds je Twitter hebt en kun je dit vergelijken met een ander! Ben jij het meest actief?',
      },
      'first-to-follow': {
        description: 'Zie wanneer je iemand gevolgd hebt en andersom! 😮',
        longDescription: 'Met First To Follow kun je de datum en tijd ontdekken waarop je een ander gevolgd hebt op Twitter, en andersom! Wie was er eerst?',
      },
      'emoji-mood': {
        description: 'Welke emojis tweet je het vaakst? 🤖',
        longDescription: 'Dankzij Emoji Mood weet je over welke emoties je het vaakst tweet... Wil je wedden?',
      },
      'new-years-kiss': {
        description: 'Wie kus jij dit jaar onder de mistletoe? 😘',
        longDescription: 'Hoe dit werkt, is ons geheimpje. Wat we wel kunnen zeggen is dat je om middernacht iemand zult zoenen!',
      },

    },

  },

  /* Pages */
  _pg: {

    /* Welcome page */
    welcome: {
      title: 'Welkom',
      welcomeToAffinitweet: 'Welkom op Affinitweet&nbsp;&nbsp;🎉',
      helloYou: 'Hallo {username}&nbsp;&nbsp;😊',
      proudToWelcomeYou: 'Hoi {username}, aangenaam kennis te maken. Welkom aan boord met onze meer dan 6 miljoen gebruikers!',
      onboardingCreation: 'We zijn blij je weer terug te hebben! We hebben deze onboarding in elkaar gezet zodat jij alles weet voordat anderen het weten...',
      next: 'Volgende',
      littleQuestion: 'Vraagje...',
      doYouWantToFollowUs: 'We updaten Affinitweet vaak, wil je ons volgen op Twitter om te zien wanneer we nieuwe functies uitbrengen?',
      iWantToFollowYou: 'Ik wil je volgen 😊',
      iDontWantToFollowYou: 'Nee, bedankt voor het aanbod!',
      great: 'Geweldig&nbsp;&nbsp;🥰',
      doYouWantToEnableNotifications: 'Nu je hier toch bent, wil je ook meldingen ontvangen over onze tweets zodat je de eerste bent om onze functies te testen?',
      iWantToBeNotified: 'Ik wil ook meldingen ontvangen 😇',
      iDontWantToBeNotified: 'Nee, alleen de tweets zien is goed genoeg voor mij!',
      noProblem: 'Geen probleem&nbsp;&nbsp;😉',
      noProblemDescription: 'Je hebt ook gelijk, we kennen elkaar amper! Misschien een andere keer dan maar. We hopen dat je plezier hebt met Affinitweet 💜',
      nice: 'Te gek&nbsp;&nbsp;🤗',
      niceDescription: 'Tik... tik... en tik!<br />Gelukt, je volgt ons nu op Twitter! Heel erg bedankt en veel plezier met Affinitweet 💜',
      awesome: 'Super&nbsp;&nbsp;😍',
      awesomeDescription: 'Tik... tik... en tik!<br />Gelukt, je volgt ons nu op Twitter en meldingen zijn ingeschakeld! Heel erg bedankt en veel plezier met Affinitweet 💜',
      uhoh: 'Oei... 😕',
      uhohDescription: 'Twitter, je hebt een probleempje...<br />Helaas kan Twitter je ons momenteel niet laten volgen. <u>Klik op de volgknop</u> om het zelf te doen 😊',
      letsGo: 'Klaar voor de start, af!',
    },

    /* Home page */
    index: {
      title: 'Start',
      description: 'De beste plek om met vrienden plezier te hebben op Twitter! Bekijk statistieken en meer!',
      titleH1: 'De beste plek om met vrienden plezier te hebben op Twitter!',
      titleH2: 'Bekijk statistieken en meer!',
      highlights: 'Hoogtepunten',
      generatedResults: 'Prachtige, gegenereerde resultaten',
      generatedResultsDescription: 'Affinitweet staat bekend om zijn prachtige, gegenereerde afbeeldingen. We gebruiken de beste tools voor je resultaten.',
      userConsentPrivacy: 'Gebruikerstoestemming en -privacy',
      userConsentPrivacyDescription: 'Alles wat we met je data doen op Affinitweet is uitgelegd in ons privacybeleid. Geen verassingen, geen automatisch volgen en geen automatische tweets.',
      worldFamousLeader: 'Wereldbekende marktleider',
      worldFamousLeaderDescription: 'Affinitweet is geopend in februari 2014 en meer dan twee miljoen gebruikers gebruiken onze diensten, overal ter wereld.',
      fastRealTimeResults: 'Razendsnelle, realtime resultaten',
      fastRealTimeResultsDescription: "We hebben Affinitweet gebouwd met de nieuwste websnufjes, dus het is zo snel mogelijk en realtime.",
      noAdsNoVirus: 'Geen advertenties en virussen',
      noAdsNoVirusDescription: "Affinitweet is puur voor vermaak gebouwd, dus geen virussen en maar 2 advertenties over de hele website (geen pop-ups of doorverwijzingen).",
      multilingualOpen: 'Meertalig en open',
      multilingualOpenDescription: 'Affinitweet is beschikbaar in meerdere talen en iedereen kan meehelpen en eigen talen toevoegen.',
      trustpilotH1: "Bekijk onze reviews op Trustpilot!",
      trustpilotH2: 'We krijgen van onze gebruikers een {rate}, ben jij de volgende om ons te beoordelen?',
      trustpilotButton: 'Bekijk reviews en beoordeel ons',
      statistics: 'Statistieken',
      totalUsers: '7 miljoen',
      totalUsersDescription: 'Gebruikers die ons en onze diensten vertrouwen',
      monthlyUsers: '400 000',
      monthlyUsersDescription: 'Gemiddeld aantal unieke gebruikers die elke maand terugkomen',
      totalFeatures: '20 miljoen',
      totalFeaturesDoneDescription: 'Functies af sinds we geopend zijn in 2014',
      ourFeatures: 'Onze functies',
      seeDetailedList: 'Gedetailleerde lijst openen',
      latestNews: 'Laatste nieuws',
      getInTouch: 'Praat met ons!',
      getInTouchP1: 'We zijn altijd beschikbaar op ons Twitter-account {twitterName}.',
      getInTouchP2: 'Volg ons en wees op de hoogte van nieuwe updates en nieuws!',
      getInTouchP3: 'Voel je vrij om naar ons te tweeten of een bericht te sturen als je vragen, suggesties of problemen hebt.',
      getInTouchP4: 'Voor zakelijke doelenden kun je contact met ons opnemen via e-mail, kijk eens op de pagina {pageName}.',
    },

    /* User profile page */
    profile: {
      title: 'Profiel',
      description: 'Account, instellingen en geschiedenis op je profiel.',
      joinBeta: 'Neem deel aan het bèta-programma om functies te proberen voordat ze gelanceerd worden!',
      betaTerms: 'Het bèta-programma is geheel gratis. Sommige functies werken mogelijk niet en kunnen aangepast worden voordat ze worden uitgebracht.',
      applyForFree: 'Gratis aanmelden',
      noThanks: 'Nee, bedankt',
      profile: 'Profiel',
      history: 'Geschiedenis',
      preferences: 'Voorkeuren',
      language: 'Taal',
      by: 'door',
      addLanguage: 'Taal toevoegen...',
      contributeOnGitHub: 'bijdragen op GitHub',
      account: 'Account',
      followers: 'Volgers',
      followings: 'Volgend',
      noHistory: 'Geen geschiedenisdata.',
      autoTweet: 'Tweet-resultaten',
      autoTweetDescription: 'Check this option to automatically tweet your results. A tweet will be published once results are ready, no more.',
      saveResults: 'Save results',
      saveResultsDescription: 'Check this option to save your results in history (feature name + image + time). By default, we do not store your results.',
      emojis: 'Emojis pack',
      iOSemojis: 'iOS (Apple)',
      iOSemojisDescription: 'Your results will be generated with iOS Emojis.',
      androidEmojis: 'Android (Google)',
      androidEmojisDescription: 'Your results will be generated with Android Emojis.',
      clearHistory: 'Clear history',
      clearHistoryDescription: 'Clear your Affinitweet results history.',
      deleteAccount: 'Delete account',
      deleteAccountDescription: 'Delete your Affinitweet account, everything will be lost.',
      show: 'view',
      showMore: 'Show more...',
      saved: 'Saved',
    },

    /* Feature page */
    feature: {
      login: 'Log in to continue...',
      startFeature: "Let's go!",
      betaFeature: 'This feature is currently in beta and is available for users being part of the Beta program only. You can apply for this program if you want to test this feature.',
      applyForFree: 'Apply for free',
      results: "Here's your results!",
      tweetResults: 'Tweet results',
      tweetingResults: 'Tweeting...',
      requireAutoTweetDescription: "Do you want to enable auto-tweet results? You'll be able to deactivate this option from your profile.",
      yesEnable: 'Yes, enable',
      no: 'No',
      retry: 'Retry!',
      doYouWantToKnowMore: 'Do you want to learn more about your Twitter account?',
      discoverOtherFeatures: 'Discover more features',
    },

    /* Features listing page */
    features: {
      title: 'Features',
      description: 'Discover all our features to know everything about your Twitter account.',
      searchFeatures: 'Search features... (ex: Top Friends, Valentine...)',
      noFeatureFound: 'Unfortunately no feature matches this search... 😔',
      resetSearch: 'Reset search',
      letsGo: 'Let\'s go!',
    },

    /* Beta program page */
    'beta-program': {
      title: 'Beta program',
      description: 'Apply to the Beta program for free and try our beta features before they get released to the public!',
      betaProgramDescription: "The Beta program has been created to test new features before they get released to the public to be sure that they're working as expected. By being part of this program, you will be able to test them.",
      currentBetaFeatures: 'There\'s currently {amount} {features} in the Beta program:',
      noCurrentBetaFeatures: 'There\'s currently no feature in the Beta program, but more are coming soon!',
      fewThingsToKnow: 'Few things to know about the Beta program:',
      li1: "It's 100% free of charge",
      li2: "There's a limited number of places",
      li3: 'You can leave it when you want',
      li4: 'Dedicated & priority support on Twitter by DM',
      li5: 'Beta features might not work as expected',
      li6: 'Beta features can change at anytime',
      thanksForInterest: 'Thank you for your interest regarding the Beta program 💜',
      alreadyApplied: "You're already in the Beta program,<br />thank you so much for your interest 💜",
      leaveBetaProgram: 'Leave the Beta program',
      leavingTerms: "If you leave the Beta Program, you may not be able to apply again if there's no available places.",
      placesAvailable: '500 places available! 🎟',
      accountEligible: 'Your account is eligible to apply for the Beta program and few places are available!',
      yourEmailAddress: 'Your email address...',
      applyForFree: 'Apply for free',
      applyTerms: 'By applying to the Beta program, you agree to receive notification & promotion emails (1 per week maximum).',
      noPlaceAvailable: 'No place available 😕',
      betaProgramFull: "Unfortunately, the Beta program is full and we can't give free access at this time, but you can still try to earn an access by using the methods in the next block!",
      keepUpdated: 'We will let you know when new free access will be available on {ourTwitterAccount}.',
      ourTwitterAccount: 'our Twitter Account',
      or: 'or',
      earnYourAccess: 'Earn your access! 🎁',
      writeReview: '#1 — Write a review about us {onTrustpilot} and send us its link on our Twitter account by DM, we will then give you an access.',
      onTrustpilot: 'on Trustpilot',
      winContest: 'or #2 — Participate in our contests on {ourTwitterAccount} to win an access, follow us and enable notifications to keep updated.',
      randomDraws: 'Each of these contests ends with a random draw made on {pickaw}, so everyone have a chance to win.',
      welcomeToTheBetaProgram: 'Welcome to the Beta program! You can now test our Beta features 😊',
      seeYouSoonBetaProgram: 'Thanks for being part of the Beta program, can\'t wait to see you soon!',
    },

    /* Legal page */
    legal: {
      title: 'Legal',
      description: 'Information about us and cookies.',
      intro: 'In accordance with Article 6 of the law n° 2004-575 of 21 June 2004 on trust in the digital economy, users of the site {site} are informed of the identity of the various parties involved in its implementation and monitoring:',
      owner: 'Owner',
      creator: 'Creator',
      publisher: 'Publication manager',
      publisherText: 'The person responsible for publication is a natural person.',
      webmaster: 'Webmaster',
      host: 'Host',
      requestAddress: 'Full address available on request by email at {email}.',
      warningCookies: 'About cookies',
      p1: 'A cookie is a small text file sent to your browser via the website you are viewing. With this cookie, information about your visit is stored on the website, such as your preferred language and other settings. This may facilitate your next visit to this site and make it more useful to you. Cookies play an important role. Without cookies, using the Web could be much more frustrating.',
      t1: 'What is the applicable legal frame?',
      p2: "In amending Article 5(3) of Directive 2002/58/EC by adopting Directive 2009/136/EC, the European legislator laid down the principle that the storage of information on a user's equipment or access to information already stored should only be carried out with the user's prior consent, unless these actions are strictly necessary for the provider to deliver a service expressly requested by the user. Article 32-II of the law of 6 January 1978 takes over this principle.",
      t2: 'This site uses cookies for the following purposes:',
      'l1-1': 'To help us recognize your browser and to save the preferences you have set in your previous visits to this site',
      'l1-2': 'To help us measure and study the effectiveness of our online interactive content, features, advertising and other communications',
      'l1-3': 'To monitor the analytical data on the site, the use made of the site by users and to improve the services and content of this site.',
      t3: 'How do I delete cookies linked to my browser?',
      p3: "You can choose to disable cookies in your browser at any time by following the instructions provided in your browser's help files. You can also set your cookies directly in your browser settings:",
    },

    /* Terms of service page */
    terms: {
      title: 'Terms of service',
      description: 'Consult our general terms and conditions of use.',
      h1: 'Terms',
      p1: 'By accessing the website at {url}, you are agreeing to be bound by these terms of service, all applicable laws and regulations, and agree that you are responsible for compliance with any applicable local laws. If you do not agree with any of these terms, you are prohibited from using or accessing this site. The materials contained in this website are protected by applicable copyright and trademark law.',
      h2: 'Use Licence',
      'l1-1': "Permission is granted to temporarily download one copy of the materials (information or software) on Affinitweet's website for personal, non-commercial transitory viewing only. This is the grant of a license, not a transfer of title, and under this license you may not:",
      'l2-1': 'modify or copy the materials;',
      'l2-2': 'use the materials for any commercial purpose, or for any public display (commercial or non-commercial);',
      'l2-3': "attempt to decompile or reverse engineer any software contained on Affinitweet's website;",
      'l2-4': 'remove any copyright or other proprietary notations from the materials; or',
      'l2-5': 'transfer the materials to another person or "mirror" the materials on any other server.',
      'l1-2': 'This license shall automatically terminate if you violate any of these restrictions and may be terminated by Affinitweet at any time. Upon terminating your viewing of these materials or upon the termination of this license, you must destroy any downloaded materials in your possession whether in electronic or printed format.',
      h3: 'Disclaimer',
      'l3-1': "The materials on Affinitweet's website are provided on an 'as is' basis. Affinitweet makes no warranties, expressed or implied, and hereby disclaims and negates all other warranties including, without limitation, implied warranties or conditions of merchantability, fitness for a particular purpose, or non-infringement of intellectual property or other violation of rights.",
      'l3-2': 'Further, Affinitweet does not warrant or make any representations concerning the accuracy, likely results, or reliability of the use of the materials on its website or otherwise relating to such materials or on any sites linked to this site.',
      h4: 'Limitations',
      p2: "In no event shall Affinitweet or its suppliers be liable for any damages (including, without limitation, damages for loss of data or profit, or due to business interruption) arising out of the use or inability to use the materials on Affinitweet's website, even if Affinitweet or a Affinitweet authorized representative has been notified orally or in writing of the possibility of such damage. Because some jurisdictions do not allow limitations on implied warranties, or limitations of liability for consequential or incidental damages, these limitations may not apply to you.",
      h5: 'Accuracy of materials',
      p3: "The materials appearing on Affinitweet's website could include technical, typographical, or photographic errors. Affinitweet does not warrant that any of the materials on its website are accurate, complete or current. Affinitweet may make changes to the materials contained on its website at any time without notice. However Affinitweet does not make any commitment to update the materials.",
      h6: 'Links',
      p4: "Affinitweet has not reviewed all of the sites linked to its website and is not responsible for the contents of any such linked site. The inclusion of any link does not imply endorsement by Affinitweet of the site. Use of any such linked website is at the user's own risk.",
      h7: 'Modifications',
      p5: 'Affinitweet may revise these terms of service for its website at any time without notice. By using this website you are agreeing to be bound by the then current version of these terms of service.',
      h8: 'Governing Law',
      p6: 'These terms and conditions are governed by and construed in accordance with the laws of France and you irrevocably submit to the exclusive jurisdiction of the courts in that State or location.',
    },

    /* Data and privacy page */
    privacy: {
      title: 'Data and privacy',
      description: 'Information on how we retrieve, analyze and store your data.',
      intro: 'We take the privacy of data very seriously and in the course of our business, we want to inform our users about what we do with it. You will find below all the necessary information concerning the storage and processing of this data. Information about cookies is also available on {thatPage}.',
      storage: 'Storage',
      personalData: 'Personal data',
      p1: 'When you log into Affinitweet, we collect the information from your Twitter profile that we need in order to offer you our services. Among this information, we store your:',
      'l1-1': 'unique Twitter ID',
      'l1-2': 'username (@)',
      'l1-3': 'name',
      'l1-4': 'authentication token',
      'l1-5': 'authentication token secret',
      'l1-6': 'language',
      p2: 'The other information you can see on your profile is temporarily stored in your session, just log out to delete it.',
      i1: 'Information: these data can be deleted in their entirety and immediately on simply clicking on {button} at the bottom of {yourProfile}.',
      results: 'Results',
      p3: 'By default, Affinitweet does not store the results of what you do. However, you can activate this option to have a history of your results in your profile. Among this information, we store:',
      'l2-1': 'the user to whom the result belongs',
      'l2-2': 'the name of the feature',
      'l2-3': 'the timestamp of the result',
      i2: 'Information: these data can be deleted in their entirety and immediately by simply clicking on {button} at the bottom of {yourProfile}.',
      computing: 'Processing',
      p4: 'When you perform the various features present on the site, we make calls to the Twitter API with your previously stored tokens.',
      i3: 'Information: we use your tokens to be able being as accurate as possible in our results. Thus, if you follow one or more users with a protected account for example, we will be able to include them in the results if necessary.',
      p5: "Here's what we can be led to get:",
      'l3-1': 'your feed',
      'l3-2': 'your tweets/retweets',
      'l3-3': 'your mentions',
      'l3-4': 'your followers',
      'l3-5': 'your followings',
      p6: 'This information is only collected and processed, we do not store it.',
      publish: 'Publication',
      p7: 'When you log in to Affinitweet, we ask for basic read access to your account and write access. We will not carry out any action without your express request by activating an option from the site.',
      i4: 'Information: you can revoke the access you gave us when you logged in at any time from your {yourTwitterProfile}.',
      autoTweet: 'Automatic tweet',
      p8: 'In order to be able to use certain features, we may ask you to enable the automatic tweet option for results. If you agree to enable this option, a tweet will be published for each result with the generated image.',
      i5: 'Information: you can deactivate this option at any time from {yourProfile} in the {button} section.',
      question: 'Any questions?',
      p9: 'If you have any questions about Affinitweet, please do not hesitate to contact us via Twitter or email, we will be happy to answer you!',
      thatPage: 'this page',
      yourProfile: 'your profile',
      yourTwitterProfile: 'your Twitter profile',
    },

  },

  /* Errors */
  _er: {
    cooldown: 'This feature have a %{cooldown} seconds cooldown. Please retry in:',
    unknown: 'An error has occured. Our team has been notified.',
    unknownFeature: 'Unknown feature.',
    unavailableFeature: 'Unavailable feature.',
    betaFeature: "You can't use beta features until you're appart of the Beta program.",
    invalidEmail: 'Email is invalid.',
    selfUsername: 'Type a different username than yourself.',
    badUsername: 'Bad username.',
    notEnoughData: 'Not enough tweets to analyze.',
    errorWhileRendering: 'Error while generating image.',
    accountProtected: "You can't use this feature while your account is protected.",
    targetAccountProtectedAndNotFollowing: "You can't use this feature because the targeted user is protected and not following you.",
    timeout: 'Timeout exceeded.',
    twitterError: 'Twitter returned an error:',
    twitterErrors: {
      32: 'Could not authenticate you.',
      34: 'Sorry, that page does not exist.',
      50: 'User not found.',
      63: 'User has been suspended.',
      64: 'Your account is suspended and is not permitted to access this feature.',
      87: 'Client is not permitted to perform this action.',
      88: 'Rate limit exceeded. Retry in 15 minutes',
      89: 'Invalid or expired token. Please reconnect.',
      99: 'Unable to verify your credentials.',
      130: 'Over capacity.',
      131: 'Internal error.',
      135: 'Could not authenticate you.',
      144: 'No status found with that ID.',
      179: 'Sorry, you are not authorized to see this status.',
      185: 'User is over daily status update limit.',
      186: 'Tweet needs to be a bit shorter.',
      187: 'Status is a duplicate.',
      220: 'Your credentials do not allow access to this resource.',
      261: 'Application cannot perform write actions.',
      326: 'To protect our users from spam and other malicious activity, this account is temporarily locked.',
    },
  },

}
