export default {

  /* Steps */
  _st: {
    received: 'Requête reçue par le serveur...',
    starting: 'Initialisation...',
    fetchingData: 'Récupération des données...',
    fetchingTweets: 'Récupération des tweets...',
    computingData: 'Analyse des données...',
    generatingImage: "Génération de l'image...",
    uploadingMedia: "Envoi de l'image...",
    publishingTweet: 'Publication du tweet...',
    savingResults: 'Sauvegarde des résultats...',
  },

  /* Features */
  _ft: {
    'twitter-activity': {
      basedOnLastDays: 'Basé sur les {days} derniers jours...',
      countingTweets: '... et en comptant {count} tweets :',
      interactionsReceived: 'Interactions reçues',
      last30Days: '* : 30 derniers jours',
      tweetingHours: 'Heures de tweet',
      tweetRepartition: 'Répartition des tweets',
    },
    'first-follower': {
      yourFirstFollowerIs: 'Ton premier follower est',
      dateFormat: 'le {day}/{month}/{year} à {hour}:{minute}:{second}',
    },
    'first-following': {
      yourFirstFollowingIs: 'Ton premier following est',
      dateFormat: 'le {day}/{month}/{year} à {hour}:{minute}:{second}',
    },
    'first-to-follow': {
      youAreNotFollowing: 'Tu ne suis pas {user}...',
      notFollowingYou: '{user} ne te suis pas...',
      youFollowed: 'Tu as suivi {user} :',
      followedYou: '{user} t\'a suivi :',
      dateFormat: 'à {hour}:{minute}:{second} le {day}/{month}/{year}',
      dateFormat2: 'le {day}/{month}/{year} à {hour}h',
    },
    friendships: {
      average: 'Moyenne des amitiés Twitter de',
      following: 'Tu le/la suis',
      'not-following': 'Tu ne le/la suis pas',
      followed_by: 'Il/elle te suit',
      'not-followed_by': 'Il/elle ne te suit pas',
      notifications_enabled: 'Tu es notifié.e quand il/elle tweete',
      'not-notifications_enabled': "Tu n'es pas notifié.e quand il/elle tweete",
      blocking: "Tu l'as bloqué.e",
      'not-blocking': "Tu ne l'as pas bloqué.e",
      blocked_by: 'Il/elle t\'a bloqué.e',
      'not-blocked_by': 'Il/elle ne t\'a pas bloqué.e',
      muting: "Tu l'as mis.e en sourdine",
      'not-muting': "Tu ne l'as pas mis.e en sourdine",
      want_retweets: 'Tu vois ses retweets',
      'not-want_retweets': 'Tu as caché ses retweets',
      marked_spam: "Tu l'as marqué.e comme spam",
      'not-marked_spam': "Tu ne l'as pas marqué.e comme spam",
    },
    'tweet-rate': {
      average: '{user} tweete en moyenne...',
      tweetsPerDay: '{count} fois par jour',
    },
    'common-friends': {
      friendsRemaining: '... et {count} autres amis !',
      noFriends: 'Aucun ami en commun...',
      commonFriends: 'Je partage {count} amis en commun avec {user} !',
      noCommonFriends: 'Je ne partage aucun ami en commun avec {user}...',
    },
    valentine: 'Mon Valentine {year} est',
    'stolen-kiss': 'Mon Stolen Kiss est',
    'hidden-twin': 'Mon Hidden Twin est',
    'secret-crush': 'Mon Secret Crush est',
    'may-day': "J'offre mon muguet 💐 à",
    'halloween-duo': 'Mon Halloween Duo est',
    'new-years-kiss': "Mon New Year's Kiss est",
  },

  /* Tweet content */
  _tw: {
    'first-to-follow': '{text}',
    friendships: '{text}',
    'top-friends': '{users}',
    'famous-followers': '{users}',
    'common-friends': '{text}',
    'tweet-rate': '{text}',
    'emoji-mood': '{emojis}',
    valentine: 'Cette année tu es à moi {user} ! ❤️\nEt toi, avec qui te retrouveras-tu ?',
    'twitter-activity': 'Voici les statistiques de mon compte de ces {days} derniers jours. Est-ce que tu as des meilleures interactions ?',
    'first-follower': 'Je viens de découvrir mon premier follower sur Twitter, c\'est {user} et il m\'a suivi {date} !\nQui est ton premier follower ?',
    'first-following': 'Je viens de découvrir mon premier following sur Twitter, c\'est {user} et je l\'ai suivi {date} !\nQui est ton premier following ?',
    'secret-crush': "{user} t'aime secrètement ! 😳\nDécouvre qui t'aime en secret !",
    'hidden-twin': '{user} est mon jumeau caché 😱\nDécouvre vite qui est le tien !',
    'stolen-kiss': "{user} t'embrasserait bien au coin d'une rue... 😏\nEt toi, qui t'embrasserait ?",
    'may-day': "{user}, je t'offre mon plus beau bouquet de muguet cette année ! 💐\nÀ qui offriras-tu le tien ?",
    'halloween-duo': 'Même pas besoin de me déguiser cette année pour faire peur, je suis avec {user} ! 🎃👻\nEt toi, avec qui seras-tu ?',
    'new-years-kiss': "Je te prépare mon dernier baiser de l'année et le premier de l'année suivante {user} !🙈😍\nEt toi, qui vas-tu embrasser à minuit ?",
  },

}
