export default {

  /* Layouts */
  _lt: {

    default: {
      cookiesBanner: 'Nous utilisons des cookies 🍪 pour t\'offrir la meilleure expérience possible. En continuant à utiliser notre site web, tu acceptes notre politique cookies. {button}',
      readMore: 'En savoir plus...',
    },

  },

  /* Common */
  _cm: {
    lastRevision: 'Dernière révision :',
    contactUs: 'Contacte-nous',
    followUs: 'Suis-nous',
    reviewUs: 'Évalue-nous',
    close: 'Fermer',
    cancel: 'Annuler',
  },

  /* Languages */
  _lg: {
    french: 'Français',
    english: 'Anglais',
    polish: 'Polonais',
    spanish: 'Espagnol',
    swedish: 'Suédois',
    turkish: 'Turque',
    indonesian: 'Indonésien',
    portuguese: 'Portugais',
    simplifiedChinese: 'Chinois Simplifié',
    traditionalChinese: 'Chinois Traditionnel',
    dutch: 'Néerlandais',
    german: 'Allemand',
    arabic: 'arabe',
  },

  /* Pluralization */
  _pl: {
    seconds: 'seconde | seconde | secondes',
    features: 'fonctionnalité | fonctionnalité | fonctionnalités',
    results: 'résultat | résultat | résultats',
  },

  /* Components */
  _cp: {

    /* Header component */
    header: {
      logIn: 'Connexion',
      helloYou: 'Bonjour {username} 👋🏻',
      myAccount: 'Mon compte',
      switchAccount: 'Changer de compte',
      logout: 'Déconnexion',
    },

    /* Footer component */
    footer: {
      madeWithLove: 'Affinitweet est une plateforme de statistiques et divertissement basée sur Twitter créée en 2015 avec ❤️ en France.',
      allRightsReserved: 'Tous droits réservés.',
      stripeClimate: '1% de nos revenus est reversé à des initiatives pour la réduction du CO₂.',
      about: 'À propos',
      changelog: 'Mises à jour',
      legal: 'Légal',
      partners: 'Partenaires',
    },

    stateButton: {
      hold: 'Maintenir pour confirmer',
      submit: 'Cliquer pour confirmer',
      loading: 'Action en cours...',
      cancel: 'Annuler',
    },

    clearHistory: {
      title: 'Nettoyage de l\'historique',
      description: 'En nettoyant ton historique, toutes les informations et images de tes résultats actuellement enregistrés seront supprimés.',
      description2: 'Tu ne pourras plus visualiser tes précédents résultats après ce nettoyage, souhaites-tu vraiment effectuer cette action ?',
      holdButton: 'Maintenir pour nettoyer',
      loadingButton: 'Nettoyage en cours...',
      successModal: 'Ton historique a été nettoyé.',
    },

    deleteAccount: {
      title: 'Suppression de compte',
      description: 'Quelque chose s\'est mal passé ? Dis-le nous sur notre compte Twitter afin que nous puissions nous améliorer !',
      description2: 'En supprimant ton compte, toutes les données te concernant seront supprimées, incluant ton historique. Aucune donnée ne sera conservée et tu seras automatiquement déconnecté d\'Affinitweet.',
      description3: 'Tu ne pourras plus retrouver ton compte actuel après cette suppression, souhaites-tu vraiment effectuer cette action ?',
      holdButton: 'Maintenir pour supprimer',
      loadingButton: 'Suppression en cours...',
      successModal: 'Ton compte a été supprimé.',
    },

    twitterDM: {
      startWritingToPreview: "Commence à rédiger pour voir l'aperçu ici !",
      now: 'Maintenant',
    },

    welcomeMessageEditor: {
      twitterDocumentation: "Qu'est-ce qu'un Welcome Message ? (Twitter)",
      helpdeskDocumentation: 'Comment fonctionne le Welcome Message Editor ?',
      fetchingWelcomeMessages: 'Récupération des messages de bienvenue...',
      addWelcomeMessage: 'Ajouter un message de bienvenue',
    },

    welcomeMessage: {
      creationDate: 'Créé {date} avec {source}',
      soon: 'prochainement',
      draft: 'Brouillon',
      inactive: 'Inactif',
      active: 'Actif',
      submit: 'Valider',
      cancel: 'Annuler',
      edit: 'Éditer',
      enable: 'Activer',
      disable: 'Désactiver',
      delete: 'Supprimer',
      writeContent: 'Rédige le contenu de ton message',
      writeContentPlaceholder: 'Écris ton message de bienvenue...',
      addOptionalMedia: 'Ajoute un media (facultatif)',
      filePlaceholder: 'Glisse & dépose un média ou clique ici 🖼',
      selectMessageType: 'Sélectionne le type de message',
      classic: 'Classique',
      button: 'Boutons',
      buttonLabelPlaceholder: 'Label',
      buttonURLPlaceholder: 'https://...',
      quickReply: 'Quick Reply',
      quickReplyPlaceholder: 'Label',
      quickReplyDescriptionPlaceholder: 'Description',
      previewResult: 'Visualise le rendu en temps réel',
      confirmDeleting: 'Es-tu sûr(e) de vouloir supprimer ce Welcome Message ?',
      confirmEnabling: "Es-tu sûr(e) de vouloir activer ce Welcome Message ? Cela désactivera l'autre actuellement en place.",
      confirmDisabling: 'Es-tu sûr(e) de vouloir désactiver ce Welcome Message ?',
    },

    deepLinkGenerator: {
      twitterDocumentation: "Qu'est-ce qu'un Deep Link ? (Twitter)",
      helpdeskDocumentation: 'Comment fonctionne le Deep Link Generator ?',
      inputPlaceholder: "Écris le message pré-rempli que t'enverront les utilisateurs !",
      attachWelcomeMessage: 'Attacher un message de bienvenue',
      youDontHaveWelcomeMessageYet: "Tu n'as pas encore de messages de bienvenue.",
      createNewWelcomeMessage: 'Créer un nouveau message de bienvenue',
      copyLink: 'Copier le lien',
      copied: 'Copié',
      generatedLinkWillBeHere: 'Le lien à ajouter au tweet sera automatiquement généré ici.',
    },

    idUsernameConverter: {
      helpdeskDocumentation: 'Comment fonctionne le ID <> Username Converter ?',
      entryFormat: "Format d'entrée",
      inputPlaceholder: "Écris ou colle un ou plusieurs IDs/noms d'utilisateurs ici !",
      copied: 'Copié',
      converting: 'Conversion en cours...',
      noResult: 'Aucun résultat.',
      errorOccured: 'Une erreur est survenue.',
      viewProfileOnTwitter: 'Voir le profil sur Twitter',
    },

    friendsFollowersManager: {
      helpdeskDocumentation: 'Comment fonctionne le Friends/Followers Manager ?',
      lastUpdate: 'Dernière mise à jour {date}',
      updateButton: 'Mettre à jour',
      all: 'Tous',
      followers: 'Abonnés',
      following: 'Abonnements',
      mutuals: 'Amis',
      filters: {
        title: 'Filtres',
        protected: 'Comptes protégés',
        verified: 'Comptes certifiés',
      },
      search: 'Rechercher...',
      fetching: 'Récupération des données...',
      noResults: 'Aucun résultat ne correspond à ta recherche, essaie autrement !',
      name: 'Nom',
      relationship: 'Relation',
      tweets: 'Tweets',
      registration: 'Inscription',
      showMore: 'Afficher {step} {results} de plus ({currentShowed}/{totalResults})',
      screenTooSmall: 'Écran trop petit',
      screenTooSmallDescription: "Le Friends/Followers Manager est un outil complet affichant beaucoup de données, l'utilisation sur mobile n'a pas été rendue possible pour ne pas dégrader l'expérience. Tu peux essayer de passer en mode paysage pour voir si cela fonctionne, sinon il faudra utiliser une taille d'écran plus grande 😇",
    },

    managerItem: {
      followingYou: 'Te suit',
      followedByYou: 'Suivi',
      mutualFollow: 'Suivi mutuel',
      showProfile: 'Voir le profil',
      follow: 'Suivre',
      unfollow: 'Ne plus suivre',
      sendDM: 'Envoyer un MP',
      block: 'Bloquer',
      reportAndBlock: 'Signaler et bloquer',
    },

  },

  /* Features */
  _ft: {

    new: 'Nouvelles',
    popular: 'Populaires',
    real: 'Réelles',
    fun: 'Amusantes',
    beta: 'Beta',
    others: 'Autres',

    list: {

      friendships: {
        description: 'Découvre tous les liens qui t\'unissent à la personne de ton choix ! 🙌',
        longDescription: 'Grâce au Friendships tu sauras à quel point tu es ami avec un autre utilisateur de ton choix : plus tu as de pastilles bleues, plus les liens sont forts ! Entre le pseudo Twitter de la personne choisie et découvre ton Friendships !',
      },
      'common-friends': {
        description: 'Découvre tes amis en commun avec une personne de ton choix ! 👥',
        longDescription: 'Le Common Friends permet de découvrir les abonnements/amis que tu as en commun avec une autre personne. Est-ce que tu as les mêmes goûts, et à quel point ?',
      },
      'top-friends': {
        description: 'Découvre tes meilleurs amis Twitter de ces derniers temps ! 🤗',
        longDescription: 'Le Top Friends permet de savoir qui sont tes meilleurs amis sur Twitter. Nous établissons un classement en analysant les mentions envoyées et reçues par ton compte. Ensuite nous les comptabilisons, additionnons et trions pour générer ton Top Friends !',
      },
      'famous-followers': {
        description: 'Découvre les personnes les plus populaires de tes abonnés ! 💅',
        longDescription: 'Le Famous Followers permet de connaître quelles sont les personnes ayant le plus d\'abonnés parmi tes abonnés. Nous récupérons chacun de tes abonnés ainsi que leurs nombre d\'abonnés et les trions pour générer ton Famous Followers !',
      },
      valentine: {
        description: 'On sait qui sera ton/ta Valentin(e) cette année... Et toi ? 💏',
        longDescription: 'Nous gardons secrètement l\'algorithme de cette fonctionnalité. Tout ce que l\'on est en mesure de dire c\'est qu\'on essaie de coller au mieux de la réalité, est-ce que notre Valentine saura te ravir... ?',
      },
      'twitter-activity': {
        description: 'Découvre le résumé de ton activité et tes statistiques Twitter 📊',
        longDescription: 'Grâce à Twitter Activity, tu sauras quand est-ce que tu tweetes le plus souvent, combien d\'interactions (impressions, retweets, likes, réponses) tu as eu au total et la répartition de tes tweets ces derniers temps.',
      },
      'first-follower': {
        description: 'Découvre quelle est la première personne à t\'avoir suivi sur Twitter 1️⃣',
        longDescription: 'Grâce au First Follower, tu sauras qui est ton premier follower et quand est-ce qu\'il t\'as suivi (ou en tout cas le plus vieux, car si on t\'as unfollow entre temps, on ne peut pas le savoir).',
      },
      'first-following': {
        description: 'Découvre quelle est la première personne que tu as suivie sur Twitter 1️⃣',
        longDescription: 'Grâce au First Following, tu sauras qui est ton premier following et quand est-ce que tu l\'as suivi (ou en tout cas le plus vieux, car si tu l\'as unfollow entre temps, on ne peut pas le savoir).',
      },
      'secret-crush': {
        description: "Quelqu'un t'aime en secret... et te le cache... 😳",
        longDescription: 'Nous gardons secrètement l\'algorithme de cette fonctionnalité. Tout ce que l\'on est en mesure de dire c\'est que ton Secret Crush va t\'impressionner, en bon ou en mauvais ?',
      },
      'hidden-twin': {
        description: 'Oui, tu as un jumeau caché... Mais qui est-ce ? 🤔',
        longDescription: 'Nous gardons secrètement l\'algorithme de cette fonctionnalité. Tout ce que l\'on est en mesure de dire c\'est que ton Hidden Twin va t\'impressionner, en bon ou en mauvais ?',
      },
      'stolen-kiss': {
        description: "Qui a envie de te voler un bisous au coin d'une rue ? 💋",
        longDescription: 'Nous gardons secrètement l\'algorithme de cette fonctionnalité. Tout ce que l\'on est en mesure de dire c\'est que ton Stolen Kiss va t\'impressionner, en bon ou en mauvais ?',
      },
      'may-day': {
        description: 'Pour qui sera ton plus beau bouquet cette année ? 💐',
        longDescription: 'Nous gardons secrètement l\'algorithme de cette fonctionnalité. Tout ce que l\'on est en mesure de dire c\'est que tu vas faire grand plaisir à quelqu\'un !',
      },
      'halloween-duo': {
        description: 'Avec qui feras-tu le plus peur cette année ? 🎃👻',
        longDescription: 'Nous gardons secrètement l\'algorithme de cette fonctionnalité. Tout ce que l\'on est en mesure de dire c\'est que tu vas faire peur pour Halloween cette année !',
      },
      'tweet-rate': {
        description: 'Compare ton taux de tweet avec une personne de ton choix ! 📊',
        longDescription: 'Le Tweet Rate permet de connaître le nombre de tweets que tu publies en moyenne par jour depuis ton inscription sur Twitter et compare-toi avec une autre personne ! Es-tu le plus actif ?',
      },
      'first-to-follow': {
        description: 'Découvre quand tu as suivi une personne et vice-versa ! 😮',
        longDescription: 'Le First To Follow te permet de découvrir la date et l\'heure à laquelle tu as suivi une autre personne sur Twitter, et vice-versa ! Qui des deux a suivi l\'autre en premier ?',
      },
      'emoji-mood': {
        description: 'Découvre quels sont les émojis que tu tweetes le plus 🤖',
        longDescription: 'Grâce à l\'Emoji Mood, tu découvriras quels sont les émojis que tu tweetes le plus ces derniers temps... Serais-tu prêt à parier quel est ton TOP 3 ?',
      },
      'new-years-kiss': {
        description: 'Qui vas-tu embrasser cette année sous le gui ? 😘',
        longDescription: 'Nous gardons secrètement l\'algorithme de cette fonctionnalité. Tout ce que l\'on est en mesure de dire c\'est que tu embrasseras quelqu\'un à minuit !',
      },

    },

  },

  /* Tools */
  _tl: {

    list: {

      'id-username-converter': { description: "Convertis un ou plusieurs IDs en noms d'utilisateurs et vice-versa en temps réel." },

      'welcome-message-editor': { description: "Gère les messages de bienvenue envoyés quand quelqu'un veut t'écrire un message privé." },

      'deep-link-generator': { description: 'Crée des liens personnalisés pré-remplis redirigeant vers tes messages privés.' },

      'friends-followers-manager': { description: 'Visualise et gère tes relations (abonnés et abonnements) facilement et rapidement.' },

    },

  },

  /* Pages */
  _pg: {

    /* Welcome page */
    welcome: {
      title: 'Bienvenue',
      welcomeToAffinitweet: 'Bienvenue sur Affinitweet&nbsp;&nbsp;🎉',
      helloYou: 'Bonjour {username}&nbsp;&nbsp;😊',
      proudToWelcomeYou: 'Bonjour {username}, nous sommes ravis de faire ta connaissance et heureux de t\'accueillir parmi nos plus de 10 millions d\'utilisateurs !',
      onboardingCreation: 'Nous sommes ravis de te revoir parmi nous ! On a créé ce petit onboarding pour s\'assurer que tu sois au courant de tout, avant tout le monde...',
      next: 'Suivant',
      littleQuestion: 'Petite question...',
      doYouWantToFollowUs: 'Nous mettons à jour Affinitweet régulièrement, veux-tu nous suivre sur Twitter pour savoir quand de nouvelles fonctionnalités seront disponibles ?',
      iWantToFollowYou: 'Je veux vous suivre 😊',
      iDontWantToFollowYou: 'Non merci ça ira pour l\'instant !',
      great: 'Super&nbsp;&nbsp;🥰',
      doYouWantToEnableNotifications: 'Du coup, tant qu\'à faire, est-ce que tu veux être notifié.e de nos tweets pour être le ou la première à tester nos nouvelles fonctionnalités ?',
      iWantToBeNotified: 'Je veux aussi être notifié.e 😇',
      iDontWantToBeNotified: 'Non, je veux juste les tweets !',
      noProblem: 'Ça marche&nbsp;&nbsp;😉',
      noProblemDescription: 'Après tout tu as raison, on se connaît à peine ! Peut-être une prochaine fois alors, on espère que tu t\'amuseras bien sur Affinitweet 💜',
      nice: 'Super&nbsp;&nbsp;🤗',
      niceDescription: 'Hop.. hop.... et hop !<br /><br />Ça y est, tu nous suis désormais sur Twitter ! Merci beaucoup et amuse-toi bien sur Affinitweet 💜',
      awesome: 'Génial&nbsp;&nbsp;😍',
      awesomeDescription: 'Hop.. hop.... et hop !<br /><br />Ça y est, tu nous suis désormais sur Twitter et les notifications ont été activées ! Merci beaucoup et amuse-toi bien sur Affinitweet 💜',
      uhoh: 'Oh oh... 😕',
      uhohDescription: 'Twitter, vous avez un problème...<br />Malheureusement Twitter n\'est pas capable de faire ça à ta place pour l\'instant. <u>Clique sur le bouton</u> pour le faire 😊',
      letsGo: 'C\'est parti !',
    },

    /* Home page */
    index: {
      title: 'Accueil',
      description: 'Ton compte Twitter, plus fun 😎 et plus pro 🧑‍💻',
      titleH1: 'Ton compte Twitter,',
      titleH1s: 'plus {fun} {emojiFun} plus {pro} {emojiPro}',
      fun: 'fun',
      pro: 'pro',
      titleH2: "Redécouvre ton compte Twitter à travers des dizaines de fonctionnalités et d'outils exclusifs pour gérer ton compte comme un pro.",
      heresWhyAffinitweetIsNumberOne: 'Voici pourquoi Affinitweet est le 1{sup} choix',
      sup: 'er',
      forALotOfUsers: "de plus de 10 millions d'utilisateurs à travers le monde",
      generatedResults: 'Génération de beaux résultats',
      generatedResultsDescription: "Affinitweet est connu pour ses belles générations d'images, nous utilisons les meilleurs outils pour tes résultats.",
      userConsentPrivacy: "Consentement de l'utilisateur",
      userConsentPrivacyDescription: "Tout ce que nous faisons avec tes données est expliqué dans notre politique, pas de surprise, d'auto-follow ou d'auto-tweet.",
      worldFamousLeader: 'Leader mondialement connu',
      worldFamousLeaderDescription: 'Affinitweet est ouvert depuis février 2015 et plus de 10 millions de personnes utilisent nos services, partout dans le monde.',
      fastRealTimeResults: 'Résultats rapides en temps réel',
      fastRealTimeResultsDescription: "Nous avons construit Affinitweet sur les dernières technologies, c'est donc aussi rapide que possible, et surtout en temps réel.",
      noAdsNoVirus: 'Ni pubs intrusives, ni virus',
      noAdsNoVirusDescription: "Affinitweet a été créé pour s'amuser, il n'y a aucun virus, et seulement 2 publicités sur tout le site (pas de popups, ni redirections).",
      multilingualOpen: 'Multilingues et ouvert',
      multilingualOpenDescription: 'Affinitweet est disponible en plusieurs langues, et tout le monde peut contribuer en y ajoutant la sienne.',
      new: 'Nouveau',
      proTools: 'Outils professionnels',
      toManageYourTwitterAsAPro: 'pour gérer ton compte Twitter comme un pro',
      discoverOurTools: 'Découvrir nos outils',
      whatOurUsersSaid: "Ce qu'on dit à propos de nous",
      ifYouNeedMoreTrust: "s'il faut plus de personnes et d'avis pour te convaincre",
      funFeatures: 'Fonctionnalités divertissantes',
      unlimitedAndFree: 'intéressantes ou amusantes, gratuites et sans limites',
      totalUsers: '10 millions',
      totalUsersDescription: "D'utilisateurs nous font confiance et utilisent nos services",
      monthlyUsers: '400 000',
      monthlyUsersDescription: 'Utilisateurs uniques qui reviennent tous les mois en moyenne',
      totalFeatures: '36 millions',
      totalFeaturesDoneDescription: 'Fonctionnalités utilisées depuis notre lancement en 2015',
      ourFeatures: 'Nos fonctionnalités',
      seeDetailedList: 'Voir la liste detaillée',
      getInTouch: 'Restons connectés !',
      getInTouchP1: 'Nous sommes disponibles à tout moment sur notre compte Twitter {twitterName}.',
      getInTouchP2: 'Suis-nous et sois notifié des mises à jour et choses à venir !',
      getInTouchP3: "N'hésite pas à nous envoyer un tweet ou message privé si tu as une question, suggestion ou un bug.",
      getInTouchP4: 'Pour les propositions commerciales, tu peux nous contacter par mail, retrouve-le dans nos {pageName}.',
    },

    /* User profile page */
    profile: {
      title: 'Profil',
      description: 'Comptes, paramètres et historique de ton profil.',
      joinBeta: 'Rejoins le Beta program pour tester nos fonctionnalités avant tout le monde !',
      betaTerms: 'Le Beta program est gratuit. Certaines fonctionnalités peuvent dysfonctionner et être modifiées à tout moment avant leur publication.',
      applyForFree: 'Rejoindre gratuitement',
      noThanks: 'Non, merci',
      profile: 'Profil',
      history: 'Historique',
      preferences: 'Préférences',
      language: 'Langue',
      by: 'par',
      addLanguage: 'Ajouter une langue...',
      contributeOnGitHub: 'contribuer sur GitHub',
      account: 'Compte',
      followers: 'Abonnés',
      following: 'Abonnements',
      noHistory: "Pas d'historique.",
      autoTweet: 'Tweeter les résultats',
      autoTweetDescription: 'Coche cette option pour tweeter automatiquement les résultats. Un tweet contenant le résultat de celles-ci sera publié sur ton profil, rien de plus.',
      saveResults: 'Enregistrer les résultats',
      saveResultsDescription: 'Coche cette option pour sauvegarder tes résultats dans l\'historique (nom de la fonctionnalité + image + date). Par défaut, nous ne les sauvegardons pas.',
      emojis: "Pack d'émojis",
      iOSemojis: 'iOS (Apple)',
      iOSemojisDescription: 'Tes résultats seront générés avec les émojis iOS.',
      androidEmojis: 'Android (Google)',
      androidEmojisDescription: 'Tes résultats seront générés avec les émojis Android.',
      clearHistory: "Nettoyer l'historique",
      clearHistoryDescription: "Supprime l'historique de tes résultats Affinitweet.",
      deleteAccount: 'Supprimer mon compte',
      deleteAccountDescription: 'Supprime ton compte Affinitweet, tout sera perdu.',
      show: 'afficher',
      showMore: 'Voir plus...',
      saved: 'Sauvegardé',
    },

    /* Feature page */
    feature: {
      login: 'Connecte-toi pour continuer...',
      startFeature: 'En avant !',
      betaFeature: 'Cette fonctionnalité est actuellement en beta et est disponible pour les utilisateurs faisant partie du Beta program uniquement. Tu peux rejoindre le Beta program si tu veux tester cette fonctionnalité.',
      applyForFree: 'Rejoindre gratuitement',
      results: 'Voici tes résultats !',
      tweetResults: 'Tweeter les résultats !',
      tweetingResults: 'Publication du tweet...',
      requireAutoTweetDescription: 'Veux-tu activer le tweet automatique des résultats ? Tu peux désactiver cette option depuis ton profil.',
      yesEnable: 'Oui, activer',
      no: 'Non',
      retry: 'Réessayer !',
      doYouWantToKnowMore: 'Tu veux apprendre d\'autres choses à propos de ton compte Twitter ?',
      discoverOtherFeatures: 'Découvrir plus de fonctionnalités',
    },

    /* Features listing page */
    features: {
      title: 'Fonctionnalités',
      description: 'Découvre toutes nos fonctionnalités pour tout savoir sur ton compte Twitter.',
      ourFeatures: 'Voici la liste de toutes nos fonctionnalités {theyAreAllFree} générant chacune une image basée sur les données de ton compte Twitter ! Si tu cherches une fonctionnalité en particulier, tu peux utiliser le champ de recherche ci-dessous.',
      theyAreAllFree: 'toutes entièrement gratuites',
      searchFeatures: 'Chercher des fonctionnalités... (ex : Top Friends, Valentine...)',
      noFeatureFound: 'Malheureusement aucune fonctionnalité ne correspond à cette recherche... 😔',
      resetSearch: 'Réinitialiser la recherche',
      letsGo: 'Allons-y !',
    },

    tool: {
      restrictedTool: "Cet outil est en mode prévisualisation car il est reservé aux utilisateurs Pro. Les données affichées sont factices afin de simuler une utilisation de l'outil.",
      becomePro: 'Devenir Pro',
    },

    /* Tools listing page */
    tools: {
      title: 'Outils',
      description: "Voici la liste de tous nos outils ayant vocation à améliorer la gestion de ton compte Twitter de diverses manières. Ces outils entrent dans le cadre d'{affinitweetPro}, un achat unique permettant d'accéder à tous ces outils et bien plus encore, pour toujours.",
    },

    /* Beta program page */
    'beta-program': {
      title: 'Beta program',
      description: "Rejoins le Beta program gratuitement et teste nos fonctionnalités beta avant qu'elles ne soient disponibles au grand public.",
      betaProgramDescription: "Le Beta program a été créé pour tester de nouvelles fonctionnalités avant qu'elles ne soient disponibles au public pour être sûr qu'elles fonctionnent correctement. En rejoignant ce programme, tu pourras les tester.",
      currentBetaFeatures: 'Il y a actuellement {amount} {features} dans le Beta program :',
      noCurrentBetaFeatures: 'Il n\'y a actuellement aucune fonctionnalité dans le Beta program, mais elles arrivent bientôt !',
      fewThingsToKnow: 'Quelques points à propos du Beta program :',
      li1: "C'est 100% gratuit",
      li2: 'Il y a un nombre de places limité',
      li3: 'Tu peux le quitter à tout moment',
      li4: 'Support dédié et privilégié sur Twitter par MP',
      li5: 'Les fonctionnalités peuvent ne pas fonctionner',
      li6: 'Les fonctionnalités peuvent changer à tout moment',
      thanksForInterest: 'Merci pour ton intérêt pour le Beta program 💜',
      alreadyApplied: 'Tu fais déjà partie du Beta program,<br />merci beaucoup pour ton intérêt 💜',
      leaveBetaProgram: 'Quitter le Beta program',
      leavingTerms: "Si tu quittes le Beta program, tu pourrais ne plus le rejoindre s'il n'y a plus de places disponibles.",
      placesAvailable: '500 places disponibles ! 🎟',
      proPlace: 'Voici ta place privilégiée 👑',
      accountEligible: 'Ton compte est éligible au Beta program et quelques places sont disponibles !',
      yourEmailAddress: 'Ton adresse mail...',
      applyForFree: 'Rejoindre gratuitement',
      applyTerms: 'En rejoignant le Beta program, tu acceptes de recevoir nos notifications par email (1 par semaine maximum).',
      noPlaceAvailable: 'Aucune place disponible 😕',
      betaProgramFull: "Malheureusement le Beta program est complet et nous ne pouvons donner davantage d'accès gratuits, mais tu peux toujours essayer d'en gagner en utilisant les méthodes d'à côté !",
      keepUpdated: 'Nous te dirons lorsque nous mettrons de nouveaux accès sur {ourTwitterAccount}.',
      ourTwitterAccount: 'notre compte Twitter',
      or: 'ou',
      earnYourAccess: 'Gagne ton accès ! 🎁',
      writeReview: '#1 — Écris une évaluation {onTrustpilot} à propos de nous et envoie-la nous sur Twitter par MP, on te donnera un accès.',
      onTrustpilot: 'sur Trustpilot',
      winContest: 'ou #2 — Participe à nos concours sur {ourTwitterAccount} pour gagner un accès, suis-nous et active les notifications.',
      randomDraws: 'Un tirage au sort sera fait sur chaque concours sur {pickaw} pour que tout le monde puisse avoir une chance de gagner.',
      welcomeToTheBetaProgram: 'Bienvenue sur le Beta program ! Tu peux maintenant tester nos fonctionnalités beta 😊',
      seeYouSoonBetaProgram: 'Merci d\'avoir fait partie de notre Beta program, on espère te revoir bientôt !',
    },

    pro: {
      title: 'Affinitweet Pro',
      description: 'Accède à des outils exclusifs et bien plus encore grâce à Affinitweet Pro ! 👑',
      alreadyLookedLikeAPro: "Tu avais déjà l'air d'un(e) Pro, mais là c'est officiel.",
      welcomeHome: 'Bienvenue chez toi, {username}',
      thanksForYourTrust: 'Merci beaucoup pour ton achat et ta confiance {username} !',
      accessToOurBestTools: 'Tu as désormais accès à nos {bestTools} et bien plus encore, alors profite',
      bestTools: 'meilleurs outils',
      couponExpireIn: 'Expire {expireIn}',
      heresACoupon: 'Voici un code de réduction que tu peux partager avec un ami pour {saveMoney} sur son Affinitweet Pro (ou tu peux le garder pour un autre compte Twitter à toi 😌). Génial, non ?',
      saveMoney: 'économiser 20%',
      shareYourCoupon: "Mais dépêche-toi, c'est un code unique et {availableSevenDays} ! 🔥",
      availableSevenDays: 'valide seulement 7 jours après ton achat',
      whatIsAffinitweetPro: "Affinitweet Pro est une offre permettant de répondre à une forte demande de nouvelles fonctionnalités pour des besoins plus professionnels, sous forme d'{uniquePurchase}.",
      uniquePurchase: "achat unique valable à vie : pas d'abonnement ni renouvellement",
      newToolsWillCome: 'De nombreux outils sont déjà présents et de nouveaux sont en développement et continueront de voir le jour au fur et à mesure. En devenant Pro, voici les avantages dont tu pourras bénéficier :',
      proAdvantages: {
        proTools: 'Accès aux outils Pro',
        proToolsDescription: 'Profite sans limite de tous les outils que nous proposons, et de ceux à venir.',
        betaProgram: 'Accès privilégié au Beta program',
        betaProgramDescription: 'Teste les futures fonctionnalités et outils en développement avant tout le monde.',
        removedAds: 'Suppression des publicités',
        removedAdsDescription: 'Navigue beaucoup plus rapidement et facilement sur Affinitweet sans publicités.',
        priorityQueue: "File d'attente prioritaire",
        priorityQueueDescription: 'Gagne du temps et génère tes résulats en priorité lors de fortes affluences.',
        unlimitedHistory: 'Historique illimité et détaillé',
        unlimitedHistoryDescription: 'Conserve les résultats des fonctionnalités sans aucune limite de temps.',
        thankYouPage: 'Page de remerciements',
        thankYouPageDescription: "Apparition sur la page de remerciements, parce qu'on ne te remerciera jamais assez.",
      },
      resetPurchase: 'Réinitialiser mon achat',
      resetPurchaseNotice: "En quittant Affinitweet Pro, tu perdras l'accès à tes avantages. Tu pourras à tout moment refaire un achat pour les retrouver sans problème.",
      uniquePurchaseLifetimeAccess: 'Achat unique, accès à vie',
      satisfiedOrRefundedUnder7Days: 'Satisfait ou remboursé sous 7 jours',
      loginToBecomePro: 'Connecte-toi pour devenir Pro',
      becomePro: 'Devenir Pro',
      contactUs: 'Nous contacter',
      orVerified: 'ou certifié',
      seeYouSoon: "Merci d'avoir fait partie de nos utilisateurs Pro, n'hésite pas à revenir quand tu veux 😊",
    },

    'thank-you': {
      title: 'Remerciements',
      description: 'Cette page rencense tous les utilisateurs qui nous soutiennent grâce à leur achat {affinitweetPro}. Ils sont actuellement au nombre de {number} et nous tenions à remercier encore une fois et publiquement chacun d\'entre eux 💜',
      searchPlaceholder: 'Rechercher un utilisateur extraordinaire... 😍',
    },

    /* Legal page */
    legal: {
      title: 'Mentions légales',
      description: 'Renseignements à propos de nous et des cookies.',
      intro: 'En vertu de l\'article 6 de la loi n° 2004-575 du 21 juin 2004 pour la confiance dans l\'économie numérique, il est précisé aux utilisateurs du site {site} l\'identité des différents intervenants dans le cadre de sa réalisation et de son suivi :',
      owner: 'Propriétaire',
      publisher: 'Responsable publication',
      publisherText: 'Le responsable de la publication est une personne physique.',
      host: 'Hébergeur',
      requestAddress: 'Adresse complète disponible sur simple demande par email à {email}.',
      warningCookies: 'À propos des cookies',
      p1: 'Un cookie est un petit fichier texte envoyé à ton navigateur via le site Web consulté. Grâce à ce cookie, des informations sur ta visite sont enregistrées sur le site Web, par exemple ta langue de prédilection et d\'autres paramètres. Cela peut faciliter ta visite suivante sur ce site et renforcer l\'utilité de ce dernier pour toi. Les cookies jouent un rôle important. Sans les cookies, l\'utilisation du Web pourrait s\'avérer beaucoup plus frustrante.',
      t1: 'Quel est le cadre juridique applicable ?',
      p2: 'En modifiant l\'article 5(3) de la directive 2002/58/CE par l\'adoption de la directive 2009/136/CE, le législateur européen a posé le principe selon lequel le stockage d\'informations sur l\'équipement d\'un utilisateur ou l\'accès à des informations déjà stockées, ne devaient être mis en œuvre qu\'avec le consentement préalable de l\'utilisateur, sauf si ces actions sont strictement nécessaires au fournisseur pour la délivrance d\'un service expressément demandé par l\'abonné ou l\'utilisateur. L\'article 32-II de la loi du 6 janvier 1978 reprend ce principe.',
      t2: 'Le présent site utilise des cookies aux fins suivantes :',
      'l1-1': 'Pour nous aider à reconnaître ton navigateur et pour enregistrer les préférences que tu as déterminées lors de tes précédentes visites sur ce site',
      'l1-2': 'Pour nous aider à mesurer et étudier l\'efficacité de notre contenu interactif en ligne, de ses caractéristiques, publicités et autres communications',
      'l1-3': 'Pour suivre les données analytiques sur le site, l\'utilisation faite du site par les utilisateurs et pour améliorer les services et les contenus du présent site',
      t3: 'Comment supprimer les cookies liés à ma navigation ?',
      p3: 'Tu peux choisir de désactiver les cookies dans ton navigateur à tout moment en suivant les instructions fournies dans les fichiers d\'aide de ton navigateur. Tu peux également paramétrer tes cookies directement dans les réglages de ton navigateur :',
    },

    /* Terms of service page */
    terms: {
      title: 'Conditions d\'utilisation',
      description: 'Consulte nos conditions générales d\'utilisation.',
      h1: 'Conditions',
      p1: "En accédant au site {url}, vous acceptez d'être lié par les présentes conditions d'utilisation, toutes les lois et réglementations applicables, et acceptez que vous êtes responsable du respect de toutes les lois locales applicables. Si vous n'êtes pas d'accord avec l'une de ces conditions, il vous est interdit d'utiliser ou d'accéder à ce site. Le matériel contenu dans ce site web est protégé par les lois applicables en matière de droit d'auteur et de marques de commerce.",
      h2: "Licence d'utilisation",
      'l1-1': "La permission est accordée de télécharger temporairement une copie du matériel (information ou logiciel) sur le site Web d'Affinitweet à des fins personnelles et non commerciales seulement. Il s'agit de l'octroi d'une licence, et non d'un transfert de titre, et en vertu de cette licence, vous ne pouvez pas le faire :",
      'l2-1': 'modifier ou copier le matériel ;',
      'l2-2': 'utiliser le matériel à des fins commerciales ou pour toute exposition publique (commerciale ou non commerciale) ;',
      'l2-3': "tenter de décompiler ou d'inverser l'ingénierie de tout logiciel contenu sur le site Web d'Affinitweet ;",
      'l2-4': "supprimer les mentions de droits d'auteur ou autres mentions de propriété des documents ; ou",
      'l2-5': 'transférer le matériel à une autre personne ou "refléter" le matériel sur tout autre serveur.',
      'l1-2': "Cette licence sera automatiquement résiliée si vous violez l'une de ces restrictions et peut être résiliée par Affinitweet à tout moment. Lorsque vous mettez fin à la consultation de ces documents ou à la résiliation de la présente licence, vous devez détruire tous les documents téléchargés en votre possession, qu'ils soient sous forme électronique ou imprimée.",
      h3: 'Clause de non-responsabilité',
      'l3-1': "Le matériel sur le site web d'Affinitweet est fourni tel quel. Affinitweet ne donne aucune garantie, expresse ou implicite, et décline et annule par la présente toutes les autres garanties, y compris, sans limitation, les garanties ou conditions implicites de qualité marchande, d'adéquation à un usage particulier ou de non-violation de la propriété intellectuelle ou d'autres violations des droits.",
      'l3-2': "De plus, Affinitweet ne garantit ni ne fait aucune représentation concernant l'exactitude, les résultats probables ou la fiabilité de l'utilisation du matériel sur son site Web ou autrement lié à ce matériel ou sur tout autre site lié à ce site.",
      h4: 'Limitations',
      p2: "En aucun cas, Affinitweet ou ses fournisseurs ne pourront être tenus responsables de tout dommage (y compris, sans limitation, les dommages pour perte de données ou de profit, ou en raison d'une interruption d'activité) résultant de l'utilisation ou de l'impossibilité d'utiliser le matériel sur le site web d'Affinitweet, même si Affinitweet ou un représentant autorisé d'Affinitweet a été informé oralement ou par écrit de la possibilité d'un tel dommage. Parce que certaines juridictions n'autorisent pas les limitations de garanties implicites, ou les limitations de responsabilité pour les dommages consécutifs ou accessoires, ces limitations peuvent ne pas s'appliquer à vous.",
      h5: 'Précision des éléments',
      p3: "Les éléments figurant sur le site web d'Affinitweet peuvent contenir des erreurs techniques, typographiques ou photographiques. Affinitweet ne garantit pas que le contenu de son site web est exact, complet ou à jour. Affinitweet peut apporter des modifications au contenu de son site web à tout moment et sans préavis. Cependant, Affinitweet ne s'engage pas à mettre à jour le matériel.",
      h6: 'Liens',
      p4: "Affinitweet n'a pas examiné tous les sites liés à son site Web et n'est pas responsable du contenu de ces sites liés. L'inclusion d'un lien n'implique pas l'approbation du site par Affinitweet. L'utilisation de ces sites web liés se fait aux risques et périls de l'utilisateur.",
      h7: 'Modifications',
      p5: "Affinitweet peut réviser les présentes conditions d'utilisation de son site web à tout moment et sans préavis. En utilisant ce site web, vous acceptez d'être lié par la version alors en vigueur des présentes conditions d'utilisation.",
      h8: 'Loi applicable',
      p6: 'Les présentes conditions générales sont régies et interprétées conformément à la législation française et vous vous soumettez irrévocablement à la juridiction exclusive des tribunaux de cet État ou de ce lieu.',
      'h9-1': 'Conditions de vente',
      p7: "Affinitweet Pro est vendu sous forme d'achat unique, à différents prix selon l'influence du compte Twitter de l'utilisateur. Lorsque le compte Twitter du client gagne en influence et dépasse un nouveau seuil, aucun supplément n'est facturé ni ne sera demandé.",
      p8: "Dans certains conditions, il se peut que l'utilisateur ne puisse pas procéder à un achat en ligne et doive contacter l'équipe d'Affinitweet pour bénéficier de tous les avantages d'Affinitweet Pro.",
      p9: 'Les prix affichés peuvent fluctuer à tout moment, sans que le client ne puisse demander un remboursement de la différence.',
      'h9-2': 'Politique de remboursement',
      p10: "Affinitweet propose une politique de remboursement \"satisfait ou remboursé\" sous 7 jours, débutant à la date d'achat, aux conditions suivantes : (1) que le code promotionnel généré à l'issue de l'achat n'ait pas été utilisé ; et (2) que l'utilisateur n'ait pas déjà bénéficié d'un remboursement par le passé.",
      p11: "Si ces conditions sont réunies, le client peut formuler une demande de remboursement en envoyant un email à {email} qui sera traitée et acceptée dans les plus brefs délais. Le remboursement sera effectif sur le compte bancaire du client dans un délai de 5 à 10 jours à partir de la date de traitement de la demande, et donnera lieu à l'annulation immédiate des tous les avantages d'Affinitweet Pro.",
      p12: "Au contraire, si ces conditions ne sont pas respectées, Affinitweet se réserve le droit de ne pas accéder à la demande de remboursement. De la même manière, aucun remboursement ou transfert d'avantages ne pourra avoir lieu, même après la période de 7 jours, si le compte Twitter devenait inutilisable d'une quelconque manière (suspendu par Twitter, changement de compte, etc...) : Affinitweet Pro est associé au compte Twitter sur lequel l'achat a été effectué. Le client devra alors se connecter avec le nouveau compte et effectuer un nouvel achat.",
      p13: "Dans de très rares cas, certains outils pourraient ne pas fonctionner (entièrement ou partiellement) si l'utilisateur possède un compte Twitter privé avec plus de 75000 abonnés ou abonnements. Le client ne pourra pas réclamer de remboursement en dehors de la période de 7 jours.",
    },

    /* Data and privacy page */
    privacy: {
      title: 'Données et confidentialité',
      description: 'Informations sur la manière dont nous récupérons, analysons et stockons tes données.',
      intro: 'Prenant très à cœur la confidentialité des données et dans le cadre de notre activité, nous souhaitons informer nos utilisateurs de ce que nous faisons de celles-ci. Tu trouveras ci-dessous toutes les informations nécessaires concernant le stockage et traitement de ces données. Des informations sur les cookies sont également disponible sur {thatPage}.',
      storage: 'Stockage',
      personalData: 'DONNÉES PERSONNELLES',
      p1: 'Lorsque tu te connectes sur Affinitweet, nous récupérons les informations de ton profil Twitter dont nous avons besoin afin que tu puisses utiliser nos services. Parmi ces informations, nous stockons ton :',
      'l1-1': 'ID unique Twitter',
      'l1-2': "nom d'utilisateur (@)",
      'l1-3': "nom d'affichage",
      'l1-4': "token d'authentification",
      'l1-5': "token d'authentification secret",
      'l1-6': 'langue',
      p2: 'Les autres informations que tu peux voir sur ton profil sont stockées temporairement dans ta session, il suffit de te déconnecter pour les effacer.',
      i1: 'Information : ces données peuvent être supprimées dans leur intégralité et immédiatement sur simple action de ta part en bas de {yourProfile} en cliquant sur {button}.',
      results: 'Résultats',
      p3: 'Par défaut, Affinitweet ne stocke pas les résultats de ce que tu fais. Tu peux cependant activer cette option pour avoir un historique de tes résultats dans ton profil. Parmi ces informations, nous stockons :',
      'l2-1': "l'utilisateur a qui appartient le résultat",
      'l2-2': 'le nom de la fonctionnalité',
      'l2-3': "l'horodatage du résultat",
      i2: 'Information : ces données peuvent être supprimées dans leur intégralité et immédiatement sur simple action de ta part en bas de {yourProfile} en cliquant sur {button}.',
      computing: 'Traitement',
      p4: "Lorsque tu effectues les différentes fonctionnalités présentes sur le site, nous faisons des appels à l'API Twitter avec tes tokens précedemment stockés.",
      i3: 'Information : nous utilisons tes tokens afin de pouvoir être au plus juste dans nos résultats. Ainsi, si tu suis un ou plusieurs utilisateurs avec un compte protégé par exemple, nous pourrons les inclure dans les résultats le cas échéant.',
      p5: 'Voici ce que nous pouvons être amenés à récupérer :',
      'l3-1': "ton fil d'actualités",
      'l3-2': 'tes tweets/retweets',
      'l3-3': 'tes mentions',
      'l3-4': "ta liste d'abonnés",
      'l3-5': "ta liste d'abonnements",
      p6: 'Ces informations sont uniquement récupérées puis traitées, nous ne les stockons pas.',
      publish: 'Publication',
      p7: "Lorsque tu te connectes sur Affinitweet, nous te demandons l'accès basique en lecture à ton compte ainsi que l'accès en écriture. Nous n'effectuerons aucune action sans que tu l'aies expressément demandé en activant une option depuis le site.",
      i4: "Information : tu peux révoquer l'accès que tu nous as donné lors de ta connexion à tout moment depuis {yourTwitterProfile}.",
      autoTweet: 'Tweet automatique',
      p8: "Afin de pouvoir utiliser certaines fonctionnalités, nous pouvons te demander d'activer l'option de tweet automatique des résultats. Si tu acceptes d'activer cette option, un tweet sera publié à chaque résultat avec l'image générée.",
      i5: 'Information : tu peux désactiver cette option à tout moment depuis {yourProfile} dans la partie {button}.',
      question: 'Une question ?',
      p9: "Si certains points ne sont pas clairs pour toi à propos d'Affinitweet ou si tu as d'autres questions, n'hésite pas à nous contacter via Twitter ou par email, nous te répondrons avec grand plaisir !",
      thatPage: 'cette page',
      yourProfile: 'ton profil',
      yourTwitterProfile: 'ton profil Twitter',
    },

  },

  /* Errors */
  _er: {
    back: 'Retour',
    reload: 'Rafraîchir',
    400: 'Mauvaise requête 🤨',
    401: 'Non authentifié 🙄',
    402: 'Paiement requis 😬',
    403: 'Accès non autorisé 😕',
    404: 'Page non trouvée 😢',
    405: 'Méthode non autorisée 🧐',
    500: 'Le serveur a retourné une erreur 😧',
    detailed400: "Il semblerait qu'il y ait un problème dans la requête.<br/>Rééssayez ou contactez-nous pour plus d'informations.",
    detailed401: 'Tu dois être connecté pour pouvoir accéder à cette page.<br/>Connecte-toi puis rééssaye.',
    detailed402: 'Tu ne peux pas accéder à cette page car elle requiert un paiment.',
    detailed403: "Tu n'as pas les droits pour accéder à cette page.<br/>Merci de nous contacter s'il s'agit d'une erreur.",
    detailed404: "Il semblerait que la page que tu cherches n'existe pas ou plus. Merci de nous contacter s'il s'agit d'un lien mort.",
    detailed405: "La méthode utilisée pour accéder à cette page n'est pas autorisée.",
    detailed500: "Le serveur a retourné une erreur. Essayez de recharger la page d'ici quelques instants.",
    cooldown: 'Cette fonctionnalité a un temps de rechargement de %{cooldown} secondes. Merci de réessayer dans :',
    unknown: "Un problème est survenu. L'équipe a été notifiée.",
    unknownFeature: 'Fonctionnalité inconnue.',
    unavailableFeature: 'Fonctionnalité non disponible.',
    betaFeature: 'Tu ne peux pas utiliser de fonctionnalité beta si tu ne fais pas partie du Beta program.',
    invalidEmail: "L'adresse email est invalide.",
    selfUsername: 'Entre un utilisateur différent de toi-même.',
    badUsername: "Nom d'utilisateur incorrect.",
    notEnoughData: 'Pas assez de tweet à analyser.',
    errorWhileRendering: 'Erreur lors de la génération.',
    accountProtected: 'Tu ne peux pas utiliser cette fontionnalité avec un compte protégé.',
    targetAccountProtectedAndNotFollowing: 'Tu ne peux pas utiliser cette fontionnalité envers un compte protégé qui ne te suit pas.',
    refreshPage: 'Merci de rafraîchir la page.',
    timeout: "Délai d'attente maximum dépassé.",
    twitterError: 'Twitter a retourné une erreur :',
    twitterErrors: {
      32: 'Impossible de t\'identifier.',
      34: "Désolé, cette page n'existe pas.",
      50: 'Utilisateur non trouvé.',
      63: "L'utilisateur a été suspendu.",
      64: 'Ton compte Twitter a été suspendu et tu ne peux accéder à cette fonctionnalité.',
      87: "Impossible d'effectuer cette action.",
      88: "Limite d'actions dépassée. Réessaye dans 15 minutes.",
      89: 'Token invalide ou expiré. Reconnecte-toi.',
      99: 'Impossible de vérifier tes identifiants.',
      130: 'Twitter est surchargé.',
      131: 'Erreur interne provenant de Twitter.',
      135: 'Impossible de t\'authentifier.',
      144: 'Tweet non trouvé avec cet ID.',
      179: "Désolé, tu n'es pas autorisé à voir ce tweet.",
      185: 'Tu as dépassé ton quota de tweet quotidien.',
      186: 'Tweet trop long.',
      187: 'Tweet dupliqué.',
      220: "Tes identifiants ne te permettent pas d'accéder à cette ressource.",
      261: "Nous n'avons pas réussi à publier les résultats.",
      326: 'Ton compte Twitter est temporairement bloqué.',
    },
  },

}
